
# Preamble ----------------------------------------------------------------

# Code author  : Ihsan Fadilah
# Email        : ifadilah@eocru.org
# Last updated : Late September 2021
# Project      : Indonesia Brain Infection Study

# This script provides reproducible code for cleaning the data. It does not have
# the dependency inherent in the script file `01-import-merge.R`. However, this
# code depends on the assumption that the format of data collection remains 
# the same throughout the project. For instance, `feversym` at the Jakarta site
# uses '9' to represent missingness and no new categories of variables are
# introduced to this dataset afterwards. If so, these new categories would be
# mistakenly read as missing data.

# Setup -------------------------------------------------------------------

library(tidyverse)  # Tidy code
library(labelled)   # Label variables
library(here)       # Navigate files
library(lubridate)  # Date-time variable
library(haven)      # Write datasets in SPSS format

# Load --------------------------------------------------------------------

ibis_raw <- here('0-data', 'ibis_merged.rds') |> read_rds()
glimpse(ibis_raw) # Take a look at the raw data (after merging)

# Clean -------------------------------------------------------------------

ibis <- ibis_raw |>

  # Redefine categories or values
  mutate(
    sex = case_when(site == 'Jakarta' & sex == 'F' ~ 'Female',
                    site == 'Jakarta' & sex == 'M' ~ 'Male',
                    site == 'Bandung' & sex == '0' ~ 'Female',
                    site == 'Bandung' & sex == '1' ~ 'Male',
                    TRUE ~ NA_character_),
    symdays = if_else(is.na(symdays) | symdays == 99999, NA_real_, symdays),
    feversym = case_when(feversym == '1' ~ TRUE,
                         feversym == '0' ~ FALSE,
                         site == 'Jakarta' & feversym == '9' ~ NA,
                         site == 'Bandung' & feversym == '8' ~ NA,
                         TRUE ~ NA),
    feverday = if_else(is.na(feverday) | feverday == 99999, NA_real_, feverday),
    headsym = case_when(headsym == '1' ~ TRUE,
                        headsym == '0' ~ FALSE,
                        site == 'Jakarta' & headsym == '9' ~ NA,
                        site == 'Bandung' & headsym == '8' ~ NA,
                        TRUE ~ NA),
    headday = if_else(is.na(headday) | headday == 99999, NA_real_, headday),
    vomitsym = case_when(vomitsym == '1' ~ TRUE,
                         vomitsym == '0' ~ FALSE,
                         site == 'Jakarta' & vomitsym == '9' ~ NA,
                         site == 'Bandung' & vomitsym == '8' ~ NA,
                         TRUE ~ NA),
    vomitday = if_else(is.na(vomitday) | vomitday == 99999, NA_real_, vomitday),
    alconsym = case_when(alconsym == '1' ~ TRUE,
                         alconsym == '0' ~ FALSE,
                         site == 'Jakarta' & alconsym == '9' ~ NA,
                         site == 'Bandung' & alconsym == '8' ~ NA,
                         TRUE ~ NA),
    alconday = if_else(is.na(alconday) | alconday == 99999, NA_real_, alconday),
    bechsym = case_when(bechsym == '1' ~ TRUE,
                        bechsym == '0' ~ FALSE,
                        site == 'Jakarta' & bechsym == '9' ~ NA,
                        site == 'Bandung' & bechsym == '8' ~ NA,
                        TRUE ~ NA),
    bechday = if_else(is.na(bechday) | bechday == 99999, NA_real_, bechday),
    seizusym = case_when(seizusym == '1' ~ TRUE,
                         seizusym == '0' ~ FALSE,
                         site == 'Jakarta' & seizusym == '9' ~ NA,
                         site == 'Bandung' & seizusym == '8' ~ NA,
                         TRUE ~ NA),
    seizuonset = if_else(is.na(seizuonset) | seizuonset == 99999,
                         NA_real_, seizuonset),
    cough = case_when(cough == '0' ~ 'None',
                      cough == '1' ~ '<2 weeks',
                      cough == '2' ~ '>2 weeks',
                      site == 'Jakarta' & cough == '9' ~ NA_character_,
                      site == 'Bandung' & cough == '8' ~ NA_character_,
                      TRUE ~ NA_character_),
    cough = ordered(cough, levels = c('None', '<2 weeks', '>2 weeks')),
    htemp = if_else(is.na(htemp) | htemp == 99999, NA_real_, htemp),
    gcs = if_else(is.na(gcs) | gcs == 99999, NA_real_, gcs),
    palsy = case_when(palsy == '1' ~ TRUE,
                      palsy == '0' ~ FALSE,
                      site == 'Jakarta' & palsy == '9' ~ NA,
                      site == 'Bandung' & palsy == '8' ~ NA,
                      TRUE ~ NA),
    papille = case_when(papille == '1' ~ TRUE,
                        papille == '0' ~ FALSE,
                        site == 'Jakarta' & papille == '9' ~ NA,
                        site == 'Bandung' & papille == '8' ~ NA,
                        TRUE ~ NA),
    neckstiff = case_when(neckstiff == '1' ~ TRUE,
                          neckstiff == '0' ~ FALSE,
                          site == 'Jakarta' & neckstiff == '9' ~ NA,
                          site == 'Bandung' & neckstiff == '8' ~ NA,
                          TRUE ~ NA),
    motordef = case_when(motordef == '1' ~ TRUE,
                         motordef == '0' ~ FALSE,
                         site == 'Jakarta' & motordef == '9' ~ NA,
                         site == 'Bandung' & motordef == '8' ~ NA,
                         TRUE ~ NA),
    hemipare = case_when(hemipare == '1' ~ TRUE,
                         hemipare == '0' ~ FALSE,
                         site == 'Jakarta' & hemipare == '9' ~ NA,
                         site == 'Bandung' & hemipare == '8' ~ NA,
                         TRUE ~ NA),
    parapare = case_when(parapare == '1' ~ TRUE,
                         parapare == '0' ~ FALSE,
                         site == 'Jakarta' & parapare == '9' ~ NA,
                         site == 'Bandung' & parapare == '8' ~ NA,
                         TRUE ~ NA),
    tetrapare = case_when(tetrapare == '1' ~ TRUE,
                          tetrapare == '0' ~ FALSE,
                         site == 'Jakarta' & tetrapare == '9' ~ NA,
                         site == 'Bandung' & tetrapare == '8' ~ NA,
                         TRUE ~ NA),
    monopare = case_when(monopare == '1' ~ TRUE,
                         monopare == '0' ~ FALSE,
                         site == 'Jakarta' & monopare == '9' ~ NA,
                         site == 'Bandung' & monopare == '8' ~ NA,
                         TRUE ~ NA),
    hemovalue = if_else(is.na(hemovalue) | hemovalue == 99999, 
                        NA_real_, hemovalue),
    wcellcvalue = if_else(is.na(wcellcvalue) | wcellcvalue == 99999, 
                          NA_real_, wcellcvalue),
    platevalue = if_else(is.na(platevalue) | platevalue == 99999, 
                         NA_real_, platevalue),
    hivvalue = case_when(hivvalue == '1' ~ 'Positive',
                         hivvalue == '0' ~ 'Negative',
                         site == 'Jakarta' & hivvalue == '9' ~ 'Not done',
                         site == 'Bandung' & hivvalue == '2' ~ 'Not done',
                         TRUE ~ NA_character_),
    cd4value = if_else(is.na(cd4value) | cd4value == 99999, 
                       NA_real_, cd4value),
    antiigg_res = case_when(antiigg_res == '1' ~ 'Positive',
                            antiigg_res == '0' ~ 'Negative',
                            site == 'Jakarta' & antiigg_res == '9' ~ 'Not done',
                            site == 'Bandung' & antiigg_res == '2' ~ 'Not done',
                            TRUE ~ NA_character_),
    hivstt = case_when(hivstt == '1' ~ 'Positive',
                       hivstt == '0' ~ 'Negative',
                         site == 'Jakarta' & hivstt == '9' ~ 'Unknown',
                         site == 'Bandung' & hivstt == '2' ~ 'Unknown',
                         TRUE ~ NA_character_),
    whcellc1 = if_else(is.na(whcellc1) | whcellc1 == 99999, 
                       NA_real_, whcellc1),
    whcellc2 = if_else(is.na(whcellc2) | whcellc2 == 99999, 
                       NA_real_, whcellc2),
    polycellc1 = if_else(is.na(polycellc1) | polycellc1 == 99999, 
                         NA_real_, polycellc1),
    polycellc2 = if_else(is.na(polycellc2) | polycellc2 == 99999, 
                       NA_real_, polycellc2),
    monocellc1 = if_else(is.na(monocellc1) | monocellc1 == 99999, 
                         NA_real_, monocellc1),
    monocellc2 = if_else(is.na(monocellc2) | monocellc2 == 99999, 
                         NA_real_, monocellc2),
    protein1 = if_else(is.na(protein1) | protein1 == 99999, 
                       NA_real_, protein1),
    protein2 = if_else(is.na(protein2) | protein2 == 99999, 
                       NA_real_, protein2),
    pblglucose1 = if_else(is.na(pblglucose1) | pblglucose1 == 99999, 
                          NA_real_, pblglucose1),
    pblglucose2 = if_else(is.na(pblglucose2) | pblglucose2 == 99999, 
                          NA_real_, pblglucose2),
    ratio_glucose1 = if_else(is.na(ratio_glucose1) | ratio_glucose1 == 99999, 
                             NA_real_, ratio_glucose1),
    ratio_glucose2 = if_else(is.na(ratio_glucose2) | ratio_glucose2 == 99999, 
                             NA_real_, ratio_glucose2),
    crag1 = case_when(crag1 == '1' ~ 'Positive',
                      crag1 == '0' ~ 'Negative',
                      site == 'Jakarta' & crag1 == '9' ~ 'Not done',
                      site == 'Bandung' & crag1 == '2' ~ 'Not done',
                      TRUE ~ NA_character_),
    crag2 = case_when(crag2 == '1' ~ 'Positive',
                      crag2 == '0' ~ 'Negative',
                      site == 'Jakarta' & crag2 == '9' ~ 'Not done',
                      site == 'Bandung' & crag2 == '2' ~ 'Not done',
                      TRUE ~ NA_character_),
    xpert1 = case_when(xpert1 == '1' ~ 'Positive',
                       xpert1 == '0' ~ 'Negative',
                       site == 'Jakarta' & xpert1 == '9' ~ 'Not done',
                       site == 'Bandung' & xpert1 == '2' ~ 'Not done',
                       TRUE ~ NA_character_),
    xpert2 = case_when(xpert2 == '1' ~ 'Positive',
                       xpert2 == '0' ~ 'Negative',
                       site == 'Jakarta' & xpert2 == '9' ~ 'Not done',
                       site == 'Bandung' & xpert2 == '2' ~ 'Not done',
                       TRUE ~ NA_character_),
    xpertrif1 = case_when(xpertrif1 == '1' ~ 'RIF-resistant',
                          xpertrif1 == '0' ~ 'RIF-sensitive',
                          TRUE ~ NA_character_),
    xpertrif2 = case_when(xpertrif2 == '1' ~ 'RIF-resistant',
                          xpertrif2 == '0' ~ 'RIF-sensitive',
                          TRUE ~ NA_character_),
    csfcmv1 = case_when(csfcmv1 == '1' ~ 'Positive',
                        csfcmv1 == '0' ~ 'Negative',
                        site == 'Jakarta' & csfcmv1 == '9' ~ 'Not done',
                        site == 'Bandung' & csfcmv1 == '2' ~ 'Not done',
                        TRUE ~ NA_character_),
    csfcmv2 = case_when(csfcmv2 == '1' ~ 'Positive',
                        csfcmv2 == '0' ~ 'Negative',
                        site == 'Jakarta' & csfcmv2 == '9' ~ 'Not done',
                        site == 'Bandung' & csfcmv2 == '2' ~ 'Not done',
                        TRUE ~ NA_character_),
    csfhsv1 = case_when(csfhsv1 == '1' ~ 'Positive',
                        csfhsv1 == '0' ~ 'Negative',
                        site == 'Jakarta' & csfhsv1 == '9' ~ 'Not done',
                        site == 'Bandung' & csfhsv1 == '2' ~ 'Not done',
                        TRUE ~ NA_character_),
    csfhsv2 = case_when(csfhsv2 == '1' ~ 'Positive',
                        csfhsv2 == '0' ~ 'Negative',
                        site == 'Jakarta' & csfhsv2 == '9' ~ 'Not done',
                        site == 'Bandung' & csfhsv2 == '2' ~ 'Not done',
                        TRUE ~ NA_character_),
    csfebv1 = case_when(csfebv1 == '1' ~ 'Positive',
                        csfebv1 == '0' ~ 'Negative',
                        site == 'Jakarta' & csfebv1 == '9' ~ 'Not done',
                        site == 'Bandung' & csfebv1 == '2' ~ 'Not done',
                        TRUE ~ NA_character_),
    csfebv2 = case_when(csfebv2 == '1' ~ 'Positive',
                        csfebv2 == '0' ~ 'Negative',
                        site == 'Jakarta' & csfebv2 == '9' ~ 'Not done',
                        site == 'Bandung' & csfebv2 == '2' ~ 'Not done',
                        TRUE ~ NA_character_),
    csfvzv1 = case_when(csfvzv1 == '1' ~ 'Positive',
                        csfvzv1 == '0' ~ 'Negative',
                        site == 'Jakarta' & csfvzv1 == '9' ~ 'Not done',
                        site == 'Bandung' & csfvzv1 == '2' ~ 'Not done',
                        TRUE ~ NA_character_),
    csfvzv2 = case_when(csfvzv2 == '1' ~ 'Positive',
                        csfvzv2 == '0' ~ 'Negative',
                        site == 'Jakarta' & csfvzv2 == '9' ~ 'Not done',
                        site == 'Bandung' & csfvzv2 == '2' ~ 'Not done',
                        TRUE ~ NA_character_),
    csfvdrl1 = case_when(csfvdrl1 == '1' ~ 'Positive',
                         csfvdrl1 == '0' ~ 'Negative',
                         site == 'Jakarta' & csfvdrl1 == '9' ~ 'Not done',
                         site == 'Bandung' & csfvdrl1 == '2' ~ 'Not done',
                         TRUE ~ NA_character_),
    csfvdrl2 = case_when(csfvdrl2 == '1' ~ 'Positive',
                         csfvdrl2 == '0' ~ 'Negative',
                         site == 'Jakarta' & csfvdrl2 == '9' ~ 'Not done',
                         site == 'Bandung' & csfvdrl2 == '2' ~ 'Not done',
                         TRUE ~ NA_character_),
    csftpha1 = case_when(csftpha1 == '1' ~ 'Positive',
                         csftpha1 == '0' ~ 'Negative',
                         site == 'Jakarta' & csftpha1 == '9' ~ 'Not done',
                         site == 'Bandung' & csftpha1 == '2' ~ 'Not done',
                         TRUE ~ NA_character_),
    csftpha2 = case_when(csftpha2 == '1' ~ 'Positive',
                         csftpha2 == '0' ~ 'Negative',
                         site == 'Jakarta' & csftpha2 == '9' ~ 'Not done',
                         site == 'Bandung' & csftpha2 == '2' ~ 'Not done',
                         TRUE ~ NA_character_),
    xraynm = case_when(xraynm == '1' ~ TRUE,
                       xraynm == '0' ~ FALSE,
                       TRUE ~ NA),
    xrayinf = case_when(xrayinf == '1' ~ TRUE,
                        xrayinf == '0' ~ FALSE,
                        TRUE ~ NA),
    xraymili = case_when(xraymili == '1' ~ TRUE,
                         xraymili == '0' ~ FALSE,
                         TRUE ~ NA),
    xraycav = case_when(xraycav == '1' ~ TRUE,
                        xraycav == '0' ~ FALSE,
                        TRUE ~ NA),
    bihernia1 = case_when(bihernia1 == '1' ~ TRUE,
                          bihernia1 == '0' ~ FALSE,
                          TRUE ~ NA),
    bihernia2 = case_when(bihernia2 == '1' ~ TRUE,
                          bihernia2 == '0' ~ FALSE,
                          TRUE ~ NA),
    bihernia3 = case_when(bihernia3 == '1' ~ TRUE,
                          bihernia3 == '0' ~ FALSE,
                          TRUE ~ NA),
    bienceph1 = case_when(bienceph1 == '1' ~ TRUE,
                          bienceph1 == '0' ~ FALSE,
                          TRUE ~ NA),
    bienceph2 = case_when(bienceph2 == '1' ~ TRUE,
                          bienceph2 == '0' ~ FALSE,
                          TRUE ~ NA),
    bienceph3 = case_when(bienceph3 == '1' ~ TRUE,
                          bienceph3 == '0' ~ FALSE,
                          TRUE ~ NA),
    staydur = if_else(is.na(staydur) | staydur == 99999, NA_real_, staydur),
    
    outcome = case_when(                                    # Clarify categories
      site == 'Bandung' & outcome == '0' ~ 'Alive',
      site == 'Bandung' & outcome == '1' ~ 'Dead',
      site == 'Bandung' & outcome == '2' ~ 'Discharged',
      site == 'Bandung' & outcome == '3' ~ 'Self-discharged',
      site == 'Bandung' & outcome == '4' ~ 'Referred to another hospital',
      site == 'Bandung' & outcome == '5' ~ 'Hospitalised',
      
      site == 'Jakarta' & outcome == '1' ~ 'Dead',
      site == 'Jakarta' & outcome == '2' ~ 'Self-discharged',
      site == 'Jakarta' & outcome == '3' ~ 'Discharged',
      site == 'Jakarta' & outcome == '4' ~ 'Referred to another hospital'
      
    ),
    
    etiomtuber = case_when(etiomtuber == '1' ~ TRUE,
                           etiomtuber == '0' ~ FALSE,
                           TRUE ~ NA),
    etmtustt = case_when(site == 'Bandung' & etmtustt == '0' ~ 'Definite',
                         site == 'Bandung' & etmtustt == '1' ~ 'Probable',
                         site == 'Bandung' & etmtustt == '2' ~ 'Possible',
                         site == 'Jakarta' & etmtustt == '1' ~ 'Definite',
                         site == 'Jakarta' & etmtustt == '2' ~ 'Probable',
                         site == 'Jakarta' & etmtustt == '3' ~ 'Possible',
                         TRUE ~ NA_character_),
    etitoxoenc = case_when(etitoxoenc == '1' ~ TRUE,
                           etitoxoenc == '0' ~ FALSE,
                           TRUE ~ NA),
    etitoxostt = case_when(site == 'Bandung' & etitoxostt == '0' ~ 'Definite',
                           site == 'Bandung' & etitoxostt == '1' ~ 'Probable',
                           site == 'Bandung' & etitoxostt == '2' ~ 'Possible',
                           site == 'Jakarta' & etitoxostt == '1' ~ 'Definite',
                           site == 'Jakarta' & etitoxostt == '2' ~ 'Probable',
                           site == 'Jakarta' & etitoxostt == '3' ~ 'Possible',
                           TRUE ~ NA_character_),
    eticryp = case_when(eticryp == '1' ~ TRUE,
                        eticryp == '0' ~ FALSE,
                        TRUE ~ NA),
    eticrypstt = case_when(site == 'Bandung' & eticrypstt == '0' ~ 'Definite',
                           site == 'Bandung' & eticrypstt == '1' ~ 'Probable',
                           site == 'Bandung' & eticrypstt == '2' ~ 'Possible',
                           site == 'Jakarta' & eticrypstt == '1' ~ 'Definite',
                           site == 'Jakarta' & eticrypstt == '2' ~ 'Probable',
                           site == 'Jakarta' & eticrypstt == '3' ~ 'Possible',
                           TRUE ~ NA_character_),
    etibac = case_when(etibac == '1' ~ TRUE,
                       etibac == '0' ~ FALSE,
                       TRUE ~ NA),
    etibacstt = case_when(site == 'Bandung' & etibacstt == '0' ~ 'Definite',
                          site == 'Bandung' & etibacstt == '1' ~ 'Probable',
                          site == 'Bandung' & etibacstt == '2' ~ 'Possible',
                          site == 'Jakarta' & etibacstt == '1' ~ 'Definite',
                          site == 'Jakarta' & etibacstt == '2' ~ 'Probable',
                          site == 'Jakarta' & etibacstt == '3' ~ 'Possible',
                          TRUE ~ NA_character_),
    etivence = case_when(etivence == '1' ~ TRUE,
                         etivence == '0' ~ FALSE,
                         TRUE ~ NA),
    etivencestt = case_when(site == 'Bandung' & etivencestt == '0' ~ 'Definite',
                            site == 'Bandung' & etivencestt == '1' ~ 'Probable',
                            site == 'Bandung' & etivencestt == '2' ~ 'Possible',
                            site == 'Jakarta' & etivencestt == '1' ~ 'Definite',
                            site == 'Jakarta' & etivencestt == '2' ~ 'Probable',
                            site == 'Jakarta' & etivencestt == '3' ~ 'Possible',
                            TRUE ~ NA_character_),
    etiothba = case_when(etiothba == '1' ~ TRUE,
                         etiothba == '0' ~ FALSE,
                         TRUE ~ NA),
    etiothmuco = case_when(etiothmuco == '1' ~ TRUE,
                           etiothmuco == '0' ~ FALSE,
                           TRUE ~ NA),
    etiothbm = case_when(etiothbm == '1' ~ TRUE,
                         etiothbm == '0' ~ FALSE,
                         TRUE ~ NA),
    etiothneu = case_when(etiothneu == '1' ~ TRUE,
                          etiothneu == '0' ~ FALSE,
                          TRUE ~ NA),
    etiohtlym = case_when(etiohtlym == '1' ~ TRUE,
                          etiohtlym == '0' ~ FALSE,
                          TRUE ~ NA),
    etiohnmdar = case_when(etiohnmdar == '1' ~ TRUE,
                           etiohnmdar == '0' ~ FALSE,
                           TRUE ~ NA),
    paticond = case_when(
      site == 'Bandung' & paticond == '0' ~ 'Alive',
      site == 'Bandung' & paticond == '1' ~ 'Dead',
      site == 'Bandung' & paticond == '2' ~ 'Lost to follow up',
      site == 'Jakarta' & paticond == '1' ~ 'Alive',
      site == 'Jakarta' & paticond == '2' ~ 'Dead',
      site == 'Jakarta' & paticond == '3' ~ 'Lost to follow up',
      TRUE ~ NA_character_),
  ) |>
  
  # Change the class
  mutate(
    sex = as_factor(sex),
    hivvalue = as_factor(hivvalue),
    antiigg_res = as_factor(antiigg_res),
    hivstt = as_factor(hivstt),
    crag1 = as_factor(crag1),
    crag2 = as_factor(crag2),
    xpert1 = as_factor(xpert1),
    xpert2 = as_factor(xpert2),
    xpertrif1 = as_factor(xpertrif1),
    xpertrif2 = as_factor(xpertrif2),
    csfcmv1 = as_factor(csfcmv1),
    csfcmv2 = as_factor(csfcmv2),
    csfhsv1 = as_factor(csfhsv1),
    csfhsv2 = as_factor(csfhsv2),
    csfebv1 = as_factor(csfebv1),
    csfebv2 = as_factor(csfebv2),
    csfvzv1 = as_factor(csfvzv1),
    csfvzv2 = as_factor(csfvzv2),
    csfvdrl1 = as_factor(csfvdrl1),
    csfvdrl2 = as_factor(csfvdrl2),
    csftpha1 = as_factor(csftpha1),
    csftpha2 = as_factor(csftpha2),
    outcome = as_factor(outcome),
    etmtustt = as_factor(etmtustt),
    etitoxostt = as_factor(etitoxostt),
    eticrypstt = as_factor(eticrypstt),
    etibacstt = as_factor(etibacstt),
    etivencestt = as_factor(etivencestt),
    paticond = as_factor(paticond)
  )
  
  # Order variable appearance in the dataset
  # ...
  
# Label variables
var_label(ibis) <- list(
  site = 'Study site',
  siteid = 'Study site ID',
  subjid = 'Unique patient ID',
  age = 'Age (years)',
  sex = 'Biological sex',
  symdays = 'Duration of symptoms (days)',
  feversym = 'Fever',
  feverday = 'Duration of fever (days)',
  headsym = 'Headache',
  headday = 'Duration of headache (days)',
  vomitsym = 'Vomiting',
  vomitday = 'Duration of vomiting (days)',
  alconsym = 'Altered conciousness',
  alconday = 'Duration of altered conciousness (days)',
  bechsym = 'Behavioural change',
  bechday = 'Duration of behavioural change (days)',
  seizusym = 'Seizure',
  seizuonset = 'Onset prior to baseline (days)',
  cough = 'Coughing',
  htemp = 'Highest recorded temperature at baseline (celcius)',
  gcs = 'Total GCS at baseline',
  palsy = 'Cranial nerve palsy',
  papille = 'Papilledema',
  neckstiff = 'Neck stiffness',
  motordef = 'Motor deficits',
  hemipare = 'Hemiparesis',
  parapare = 'Paraparesis',
  tetrapare = 'Tetraparesis',
  monopare = 'Monoparesis',
  hemovalue = 'Haemoglobin level (g/dL)',
  wcellcvalue = 'White blood cell count (in 1000 cells/μL)',
  platevalue = 'Platelet count (in 1000 cells/μL)',
  hivvalue = 'HIV test',
  cd4value = 'CD4 cell count (cells/L)',
  antiigg_res = 'Antitoxoplasma IgG',
  hivstt = 'HIV status',
  whcellc1 = 'Total white cell count (cells/μL), 1',
  whcellc2 = 'Total white cell count (cells/μL), 2',
  polycellc1 = 'Polymorphonuclear cell count (cells/μL), 1',
  polycellc2 = 'Polymorphonuclear cell count (cells/μL), 2',
  monocellc1 = 'Mononuclear cell count (cells/μL), 1',
  monocellc2 = 'Mononuclear cell count (cells/μL), 2',
  protein1 = 'Total protein (mg/dL), 1',
  protein2 = 'Total protein (mg/dL), 2',
  pblglucose1 = 'Paired blood glucose (mg/dL), 1',
  pblglucose2 = 'Paired blood glucose (mg/dL), 2',
  ratio_glucose1 = 'Glucose ratio, 1',
  ratio_glucose2 = 'Glucose ratio, 2',
  crag1 = 'Cryptococcal antigen test, 1',
  crag2 = 'Cryptococcal antigen test, 2',
  xpert1 = 'Gene Xpert, 1',
  xpert2 = 'Gene Xpert, 2',
  xpertrif1 = 'RIF resistance, 1',
  xpertrif2 = 'RIF resistance, 2',
  csfcmv1 = 'CSF PCR for CMV, 1',
  csfcmv2 = 'CSF PCR for CMV, 2',
  csfhsv1 = 'CSF PCR for HSV, 1',
  csfhsv2 = 'CSF PCR for HSV, 2',
  csfebv1 = 'CSF PCR for EBV, 1',
  csfebv2 = 'CSF PCR for EBV, 2',
  csfvzv1 = 'CSF PCR for VZV, 1',
  csfvzv2 = 'CSF PCR for VZV, 2',
  csfvdrl1 = 'CSF PCR for VDRL, 1',
  csfvdrl2 = 'CSF PCR for VDRL, 2',
  csftpha1 = 'CSF PCR for TPHA, 1',
  csftpha2 = 'CSF PCR for TPHA, 2',
  xraynm = 'Chest X-ray: Normal',
  xrayinf = 'Chest X-ray: Infiltrates',
  xraymili = 'Chest X-ray: Miliary',
  xraycav = 'Chest X-ray: Cavities',
  xray_ores = 'Chest X-ray: Other',
  bihernia1 = 'Herniation, 1',
  bihernia2 = 'Herniation, 2',
  bihernia3 = 'Herniation, 3',
  bienceph1 = 'Encephalitis, 1',
  bienceph2 = 'Encephalitis, 2',
  bienceph3 = 'Encephalitis, 3',
  staydur = 'Duration of stay (days)',
  outcome = 'Outcome',
  nonneuspec = 'Non-neuroinfection case, specified',
  etiomtuber = 'M. tuberculosis',
  etmtustt = 'M. tuberculosis status',
  etitoxoenc = 'Toxoplasma encephalitis',
  etitoxostt = 'Toxoplasma encephalitis status',
  eticryp = 'Cryptococcal meningitis',
  eticrypstt = 'Cryptococcal meningitis status',
  etibac = 'Bacterial meningitis',
  etibacstt = 'Bacterial meningitis status',
  etivence = 'Viral encephalitis',
  etivencestt = 'Viral encephalitis status',
  etiothba = 'Brain abcess',
  etiothmuco = 'Mucormycosis',
  etiothbm = 'Bacterial meningitis',
  etiothneu = 'Neurosyphilis',
  etiohtlym = 'Lymphoma',
  etiohnmdar = 'NMDAR encephalitis',
  etioothspec = 'Other aetiology',
  paticond = "Patient's condition"
)

# Take a look at the cleaned dataset
glimpse(ibis)

# Save --------------------------------------------------------------------

ibis_raw |> write_rds(here('0-data', 'ibis_cleaned.rds')) # R
ibis_raw |> write_sav(here('0-data', 'ibis_cleaned.sav')) # SPSS
ibis_raw |> write_dta(here('0-data', 'ibis_cleaned.dta')) # Stata

# Appendix ----------------------------------------------------------------

sessioninfo::platform_info()



















