# Preamble ----------------------------------------------------------------


# Code author  : Ihsan Fadilah
# Email        : ifadilah@eocru.org
# Last updated : Early February 2022
# Project      : Indonesia Brain Infection Study

# This script provides reproducible code for cleaning the data. It does not have
# the dependency inherent in the script file `01-import-merge.R`. However, this
# code depends on the assumption that the format of data collection remains 
# the same throughout the project. For instance, `feversym` at the Jakarta site
# uses '9' to represent missingness and no new categories of variables are
# introduced to this dataset afterwards. If so, these new categories would be
# mistakenly read as missing data.

# Setup -------------------------------------------------------------------

library(tidyverse)  # Tidy code
library(labelled)   # Label variables
library(here)       # Navigate files
library(lubridate)  # Date-time variable
library(haven)      # Write datasets in SPSS format

# Load --------------------------------------------------------------------

ibis_raw <- here('0-data', 'ibis_all-merged.rds') |> read_rds()
glimpse(ibis_raw) # Take a look at the raw data (after merging)

# Clean ------------------------------------------------------------------

clindastt_jkt <- ibis_raw |> 
  filter(site == 'Jakarta') |> 
  pull(clindastt) |> 
  factor(levels = c('1', '2'), labels = c('Initiated', 'Continued'))

clindastt_bdg <- ibis_raw |> 
  filter(site == 'Bandung') |> 
  pull(clindadtc) |> 
  factor(levels = c('0', '1'), labels = c('Initiated', 'Continued'))

clindastt0 <- c(clindastt_jkt, clindastt_bdg)

clindadtc_jkt <- ibis_raw |> 
  filter(site == 'Jakarta') |> 
  pull(clindadtc) |> 
  ymd()

clindadtc_bdg <- ibis_raw |> 
  filter(site == 'Bandung') |> 
  pull(clindastt) |> 
  ymd()

clindadtc0 <- c(clindadtc_jkt, clindadtc_bdg)

ibis <- ibis_raw |>
  
  # Redefine categories or values
  mutate(
    sex = case_when(site == 'Jakarta' & sex == 'F' ~ 'Female',
                    site == 'Jakarta' & sex == 'M' ~ 'Male',
                    site == 'Bandung' & sex == '0' ~ 'Female',
                    site == 'Bandung' & sex == '1' ~ 'Male',
                    TRUE ~ NA_character_),
    symdays = if_else(is.na(symdays) | symdays == 99999, NA_real_, symdays),
    feversym = case_when(feversym == '1' ~ 'Yes',
                         feversym == '0' ~ 'No',
                         site == 'Jakarta' & feversym == '9' ~ 'Unknown',
                         site == 'Bandung' & feversym == '8' ~ 'Unknown',
                         TRUE ~ NA_character_),
    feverday = if_else(is.na(feverday) | feverday == 99999, NA_real_, feverday),
    headsym = case_when(headsym == '1' ~ 'Yes',
                        headsym == '0' ~ 'No',
                        site == 'Jakarta' & headsym == '9' ~ 'Unknown',
                        site == 'Bandung' & headsym == '8' ~ 'Unknown',
                        TRUE ~ NA_character_),
    headday = if_else(is.na(headday) | headday == 99999, NA_real_, headday),
    vomitsym = case_when(vomitsym == '1' ~ 'Yes',
                         vomitsym == '0' ~ 'No',
                         site == 'Jakarta' & vomitsym == '9' ~ 'Unknown',
                         site == 'Bandung' & vomitsym == '8' ~ 'Unknown',
                         TRUE ~ NA_character_),
    vomitday = if_else(is.na(vomitday) | vomitday == 99999, NA_real_, vomitday),
    alconsym = case_when(alconsym == '1' ~ TRUE,
                         alconsym == '0' ~ FALSE,
                         site == 'Jakarta' & alconsym == '9' ~ NA,
                         site == 'Bandung' & alconsym == '8' ~ NA,
                         TRUE ~ NA),
    alconday = if_else(is.na(alconday) | alconday == 99999, NA_real_, alconday),
    bechsym = case_when(bechsym == '1' ~ 'Yes',
                        bechsym == '0' ~ 'No',
                        site == 'Jakarta' & bechsym == '9' ~ 'Unknown',
                        site == 'Bandung' & bechsym == '8' ~ 'Unknown',
                        TRUE ~ NA_character_),
    bechday = if_else(is.na(bechday) | bechday == 99999, NA_real_, bechday),
    seizusym = case_when(seizusym == '1' ~ 'Yes',
                         seizusym == '0' ~ 'No',
                         site == 'Jakarta' & seizusym == '9' ~ 'Unknown',
                         site == 'Bandung' & seizusym == '8' ~ 'Unknown',
                         TRUE ~ NA_character_),
    seizuonset = if_else(is.na(seizuonset) | seizuonset == 99999,
                         NA_real_, seizuonset),
    cough = case_when(cough == '0' ~ 'None',
                      cough == '1' ~ '<2 weeks',
                      cough == '2' ~ '>2 weeks',
                      site == 'Jakarta' & cough == '9' ~ 'Unknown',
                      site == 'Bandung' & cough == '8' ~ 'Unknown',
                      TRUE ~ NA_character_),
    # cough = ordered(cough, levels = c('None', '<2 weeks', '>2 weeks')),
    htemp = if_else(is.na(htemp) | htemp == 99999, NA_real_, htemp),
    gcs = if_else(is.na(gcs) | gcs == 99999, NA_real_, gcs),
    palsy = case_when(palsy == '1' ~ 'Yes',
                      palsy == '0' ~ 'No',
                      site == 'Jakarta' & palsy == '9' ~ 'Unknown',
                      site == 'Bandung' & palsy == '8' ~ 'Unknown',
                      TRUE ~ NA_character_),
    papille = case_when(papille == '1' ~ 'Yes',
                        papille == '0' ~ 'No',
                        site == 'Jakarta' & papille == '9' ~ 'Unknown',
                        site == 'Bandung' & papille == '8' ~ 'Unknown',
                        TRUE ~ NA_character_),
    neckstiff = case_when(neckstiff == '1' ~ 'Yes',
                          neckstiff == '0' ~ 'No',
                          site == 'Jakarta' & neckstiff == '9' ~ 'Unknown',
                          site == 'Bandung' & neckstiff == '8' ~ 'Unknown',
                          TRUE ~ NA_character_),
    motordef = case_when(motordef == '1' ~ 'Yes',
                         motordef == '0' ~ 'No',
                         site == 'Jakarta' & motordef == '9' ~ 'Unknown',
                         site == 'Bandung' & motordef == '8' ~ 'Unknown',
                         TRUE ~ NA_character_),
    hemipare = case_when(hemipare == '1' ~ 'Yes',
                         hemipare == '0' ~ 'No',
                         site == 'Jakarta' & hemipare == '9' ~ 'Unknown',
                         site == 'Bandung' & hemipare == '8' ~ 'Unknown',
                         TRUE ~ NA_character_),
    parapare = case_when(parapare == '1' ~ 'Yes',
                         parapare == '0' ~ 'No',
                         site == 'Jakarta' & parapare == '9' ~ 'Unknown',
                         site == 'Bandung' & parapare == '8' ~ 'Unknown',
                         TRUE ~ NA_character_),
    tetrapare = case_when(tetrapare == '1' ~ 'Yes',
                          tetrapare == '0' ~ 'No',
                          site == 'Jakarta' & tetrapare == '9' ~ 'Unknown',
                          site == 'Bandung' & tetrapare == '8' ~ 'Unknown',
                          TRUE ~ NA_character_),
    monopare = case_when(monopare == '1' ~ 'Yes',
                         monopare == '0' ~ 'No',
                         site == 'Jakarta' & monopare == '9' ~ 'Unknown',
                         site == 'Bandung' & monopare == '8' ~ 'Unknown',
                         TRUE ~ NA_character_),
    hemovalue = if_else(is.na(hemovalue) | hemovalue == 99999, 
                        NA_real_, hemovalue),
    wcellcvalue = if_else(is.na(wcellcvalue) | wcellcvalue == 99999, 
                          NA_real_, wcellcvalue),
    platevalue = if_else(is.na(platevalue) | platevalue == 99999, 
                         NA_real_, platevalue),
    hivvalue = case_when(hivvalue == '1' ~ 'Positive',
                         hivvalue == '0' ~ 'Negative',
                         site == 'Jakarta' & hivvalue == '9' ~ 'Not done',
                         site == 'Bandung' & hivvalue == '2' ~ 'Not done',
                         TRUE ~ NA_character_),
    cd4value = if_else(is.na(cd4value) | cd4value == 99999, 
                       NA_real_, cd4value),
    antiigg_res = case_when(antiigg_res == '1' ~ 'Positive',
                            antiigg_res == '0' ~ 'Negative',
                            site == 'Jakarta' & antiigg_res == '9' ~ 'Not done',
                            site == 'Bandung' & antiigg_res == '2' ~ 'Not done',
                            TRUE ~ NA_character_),
    hivstt = case_when(hivstt == '1' ~ 'Positive',
                       hivstt == '0' ~ 'Negative',
                         site == 'Jakarta' & hivstt == '9' ~ 'Unknown',
                         site == 'Bandung' & hivstt == '2' ~ 'Unknown',
                         TRUE ~ NA_character_),
    whcellc1 = if_else(is.na(whcellc1) | whcellc1 == 99999, 
                       NA_real_, whcellc1),
    whcellc2 = if_else(is.na(whcellc2) | whcellc2 == 99999, 
                       NA_real_, whcellc2),
    polycellc1 = if_else(is.na(polycellc1) | polycellc1 == 99999, 
                         NA_real_, polycellc1),
    polycellc2 = if_else(is.na(polycellc2) | polycellc2 == 99999, 
                         NA_real_, polycellc2),
    monocellc1 = if_else(is.na(monocellc1) | monocellc1 == 99999, 
                         NA_real_, monocellc1),
    monocellc2 = if_else(is.na(monocellc2) | monocellc2 == 99999, 
                         NA_real_, monocellc2),
    protein1 = if_else(is.na(protein1) | protein1 == 99999, 
                       NA_real_, protein1),
    protein2 = if_else(is.na(protein2) | protein2 == 99999, 
                       NA_real_, protein2),
    pblglucose1 = if_else(is.na(pblglucose1) | pblglucose1 == 99999, 
                          NA_real_, pblglucose1),
    pblglucose2 = if_else(is.na(pblglucose2) | pblglucose2 == 99999, 
                          NA_real_, pblglucose2),
    ratio_glucose1 = if_else(is.na(ratio_glucose1) | ratio_glucose1 == 99999, 
                             NA_real_, ratio_glucose1),
    ratio_glucose2 = if_else(is.na(ratio_glucose2) | ratio_glucose2 == 99999, 
                             NA_real_, ratio_glucose2),
    crag1 = case_when(crag1 == '1' ~ 'Positive',
                      crag1 == '0' ~ 'Negative',
                      site == 'Jakarta' & crag1 == '9' ~ 'Not done',
                      site == 'Bandung' & crag1 == '2' ~ 'Not done',
                      TRUE ~ NA_character_),
    crag2 = case_when(crag2 == '1' ~ 'Positive',
                      crag2 == '0' ~ 'Negative',
                      site == 'Jakarta' & crag2 == '9' ~ 'Not done',
                      site == 'Bandung' & crag2 == '2' ~ 'Not done',
                      TRUE ~ NA_character_),
    xpert1 = case_when(xpert1 == '1' ~ 'Positive',
                       xpert1 == '0' ~ 'Negative',
                       site == 'Jakarta' & xpert1 == '9' ~ 'Not done',
                       site == 'Bandung' & xpert1 == '2' ~ 'Not done',
                       TRUE ~ NA_character_),
    xpert2 = case_when(xpert2 == '1' ~ 'Positive',
                       xpert2 == '0' ~ 'Negative',
                       site == 'Jakarta' & xpert2 == '9' ~ 'Not done',
                       site == 'Bandung' & xpert2 == '2' ~ 'Not done',
                       TRUE ~ NA_character_),
    xpertrif1 = case_when(xpertrif1 == '1' ~ 'RIF-resistant',
                          xpertrif1 == '0' ~ 'RIF-sensitive',
                          TRUE ~ NA_character_),
    xpertrif2 = case_when(xpertrif2 == '1' ~ 'RIF-resistant',
                          xpertrif2 == '0' ~ 'RIF-sensitive',
                          TRUE ~ NA_character_),
    csfcmv1 = case_when(csfcmv1 == '1' ~ 'Positive',
                        csfcmv1 == '0' ~ 'Negative',
                        site == 'Jakarta' & csfcmv1 == '9' ~ 'Not done',
                        site == 'Bandung' & csfcmv1 == '2' ~ 'Not done',
                        TRUE ~ NA_character_),
    csfcmv2 = case_when(csfcmv2 == '1' ~ 'Positive',
                        csfcmv2 == '0' ~ 'Negative',
                        site == 'Jakarta' & csfcmv2 == '9' ~ 'Not done',
                        site == 'Bandung' & csfcmv2 == '2' ~ 'Not done',
                        TRUE ~ NA_character_),
    csfhsv1 = case_when(csfhsv1 == '1' ~ 'Positive',
                        csfhsv1 == '0' ~ 'Negative',
                        site == 'Jakarta' & csfhsv1 == '9' ~ 'Not done',
                        site == 'Bandung' & csfhsv1 == '2' ~ 'Not done',
                        TRUE ~ NA_character_),
    csfhsv2 = case_when(csfhsv2 == '1' ~ 'Positive',
                        csfhsv2 == '0' ~ 'Negative',
                        site == 'Jakarta' & csfhsv2 == '9' ~ 'Not done',
                        site == 'Bandung' & csfhsv2 == '2' ~ 'Not done',
                        TRUE ~ NA_character_),
    csfebv1 = case_when(csfebv1 == '1' ~ 'Positive',
                        csfebv1 == '0' ~ 'Negative',
                        site == 'Jakarta' & csfebv1 == '9' ~ 'Not done',
                        site == 'Bandung' & csfebv1 == '2' ~ 'Not done',
                        TRUE ~ NA_character_),
    csfebv2 = case_when(csfebv2 == '1' ~ 'Positive',
                        csfebv2 == '0' ~ 'Negative',
                        site == 'Jakarta' & csfebv2 == '9' ~ 'Not done',
                        site == 'Bandung' & csfebv2 == '2' ~ 'Not done',
                        TRUE ~ NA_character_),
    csfvzv1 = case_when(csfvzv1 == '1' ~ 'Positive',
                        csfvzv1 == '0' ~ 'Negative',
                        site == 'Jakarta' & csfvzv1 == '9' ~ 'Not done',
                        site == 'Bandung' & csfvzv1 == '2' ~ 'Not done',
                        TRUE ~ NA_character_),
    csfvzv2 = case_when(csfvzv2 == '1' ~ 'Positive',
                        csfvzv2 == '0' ~ 'Negative',
                        site == 'Jakarta' & csfvzv2 == '9' ~ 'Not done',
                        site == 'Bandung' & csfvzv2 == '2' ~ 'Not done',
                        TRUE ~ NA_character_),
    csfvdrl1 = case_when(csfvdrl1 == '1' ~ 'Positive',
                         csfvdrl1 == '0' ~ 'Negative',
                         site == 'Jakarta' & csfvdrl1 == '9' ~ 'Not done',
                         site == 'Bandung' & csfvdrl1 == '2' ~ 'Not done',
                         TRUE ~ NA_character_),
    csfvdrl2 = case_when(csfvdrl2 == '1' ~ 'Positive',
                         csfvdrl2 == '0' ~ 'Negative',
                         site == 'Jakarta' & csfvdrl2 == '9' ~ 'Not done',
                         site == 'Bandung' & csfvdrl2 == '2' ~ 'Not done',
                         TRUE ~ NA_character_),
    csftpha1 = case_when(csftpha1 == '1' ~ 'Positive',
                         csftpha1 == '0' ~ 'Negative',
                         site == 'Jakarta' & csftpha1 == '9' ~ 'Not done',
                         site == 'Bandung' & csftpha1 == '2' ~ 'Not done',
                         TRUE ~ NA_character_),
    csftpha2 = case_when(csftpha2 == '1' ~ 'Positive',
                         csftpha2 == '0' ~ 'Negative',
                         site == 'Jakarta' & csftpha2 == '9' ~ 'Not done',
                         site == 'Bandung' & csftpha2 == '2' ~ 'Not done',
                         TRUE ~ NA_character_),
    xraynm = case_when(xraynm == '1' ~ TRUE,
                       xraynm == '0' ~ FALSE,
                       TRUE ~ NA),
    xrayinf = case_when(xrayinf == '1' ~ TRUE,
                        xrayinf == '0' ~ FALSE,
                        TRUE ~ NA),
    xraymili = case_when(xraymili == '1' ~ TRUE,
                         xraymili == '0' ~ FALSE,
                         TRUE ~ NA),
    xraycav = case_when(xraycav == '1' ~ TRUE,
                        xraycav == '0' ~ FALSE,
                        TRUE ~ NA),
    bihernia1 = case_when(bihernia1 == '1' ~ TRUE,
                          bihernia1 == '0' ~ FALSE,
                          TRUE ~ NA),
    bihernia2 = case_when(bihernia2 == '1' ~ TRUE,
                          bihernia2 == '0' ~ FALSE,
                          TRUE ~ NA),
    bihernia3 = case_when(bihernia3 == '1' ~ TRUE,
                          bihernia3 == '0' ~ FALSE,
                          TRUE ~ NA),
    bienceph1 = case_when(bienceph1 == '1' ~ TRUE,
                          bienceph1 == '0' ~ FALSE,
                          TRUE ~ NA),
    bienceph2 = case_when(bienceph2 == '1' ~ TRUE,
                          bienceph2 == '0' ~ FALSE,
                          TRUE ~ NA),
    bienceph3 = case_when(bienceph3 == '1' ~ TRUE,
                          bienceph3 == '0' ~ FALSE,
                          TRUE ~ NA),
    staydur = if_else(is.na(staydur) | staydur == 99999, NA_real_, staydur),
    
    outcome = case_when(                                    # Clarify categories
      site == 'Bandung' & outcome == '0' ~ 'Alive',
      site == 'Bandung' & outcome == '1' ~ 'Dead',
      site == 'Bandung' & outcome == '2' ~ 'Discharged',
      site == 'Bandung' & outcome == '3' ~ 'Self-discharged',
      site == 'Bandung' & outcome == '4' ~ 'Referred to another hospital',
      site == 'Bandung' & outcome == '5' ~ 'Hospitalised',
      
      site == 'Jakarta' & outcome == '1' ~ 'Dead',
      site == 'Jakarta' & outcome == '2' ~ 'Self-discharged',
      site == 'Jakarta' & outcome == '3' ~ 'Discharged',
      site == 'Jakarta' & outcome == '4' ~ 'Referred to another hospital'
      
    ),
    
    etiomtuber = case_when(etiomtuber == '1' ~ TRUE,
                           etiomtuber == '0' ~ FALSE,
                           TRUE ~ NA),
    etmtustt = case_when(site == 'Bandung' & etmtustt == '0' ~ 'Definite',
                         site == 'Bandung' & etmtustt == '1' ~ 'Probable',
                         site == 'Bandung' & etmtustt == '2' ~ 'Possible',
                         site == 'Jakarta' & etmtustt == '1' ~ 'Definite',
                         site == 'Jakarta' & etmtustt == '2' ~ 'Probable',
                         site == 'Jakarta' & etmtustt == '3' ~ 'Possible',
                         TRUE ~ NA_character_),
    etitoxoenc = case_when(etitoxoenc == '1' ~ TRUE,
                           etitoxoenc == '0' ~ FALSE,
                           TRUE ~ NA),
    etitoxostt = case_when(site == 'Bandung' & etitoxostt == '0' ~ 'Definite',
                           site == 'Bandung' & etitoxostt == '1' ~ 'Probable',
                           site == 'Bandung' & etitoxostt == '2' ~ 'Possible',
                           site == 'Jakarta' & etitoxostt == '1' ~ 'Definite',
                           site == 'Jakarta' & etitoxostt == '2' ~ 'Probable',
                           site == 'Jakarta' & etitoxostt == '3' ~ 'Possible',
                           TRUE ~ NA_character_),
    eticryp = case_when(eticryp == '1' ~ TRUE,
                        eticryp == '0' ~ FALSE,
                        TRUE ~ NA),
    eticrypstt = case_when(site == 'Bandung' & eticrypstt == '0' ~ 'Definite',
                           site == 'Bandung' & eticrypstt == '1' ~ 'Probable',
                           site == 'Bandung' & eticrypstt == '2' ~ 'Possible',
                           site == 'Jakarta' & eticrypstt == '1' ~ 'Definite',
                           site == 'Jakarta' & eticrypstt == '2' ~ 'Probable',
                           site == 'Jakarta' & eticrypstt == '3' ~ 'Possible',
                           TRUE ~ NA_character_),
    etibac = case_when(etibac == '1' ~ TRUE,
                       etibac == '0' ~ FALSE,
                       TRUE ~ NA),
    etibacstt = case_when(site == 'Bandung' & etibacstt == '0' ~ 'Definite',
                          site == 'Bandung' & etibacstt == '1' ~ 'Probable',
                          site == 'Bandung' & etibacstt == '2' ~ 'Possible',
                          site == 'Jakarta' & etibacstt == '1' ~ 'Definite',
                          site == 'Jakarta' & etibacstt == '2' ~ 'Probable',
                          site == 'Jakarta' & etibacstt == '3' ~ 'Possible',
                          TRUE ~ NA_character_),
    etivence = case_when(etivence == '1' ~ TRUE,
                         etivence == '0' ~ FALSE,
                         TRUE ~ NA),
    etivencestt = case_when(site == 'Bandung' & etivencestt == '0' ~ 'Definite',
                            site == 'Bandung' & etivencestt == '1' ~ 'Probable',
                            site == 'Bandung' & etivencestt == '2' ~ 'Possible',
                            site == 'Jakarta' & etivencestt == '1' ~ 'Definite',
                            site == 'Jakarta' & etivencestt == '2' ~ 'Probable',
                            site == 'Jakarta' & etivencestt == '3' ~ 'Possible',
                            TRUE ~ NA_character_),
    etiothba = case_when(etiothba == '1' ~ TRUE,
                         etiothba == '0' ~ FALSE,
                         TRUE ~ NA),
    etiothmuco = case_when(etiothmuco == '1' ~ TRUE,
                           etiothmuco == '0' ~ FALSE,
                           TRUE ~ NA),
    etiothbm = case_when(etiothbm == '1' ~ TRUE,
                         etiothbm == '0' ~ FALSE,
                         TRUE ~ NA),
    etiothneu = case_when(etiothneu == '1' ~ TRUE,
                          etiothneu == '0' ~ FALSE,
                          TRUE ~ NA),
    etiohtlym = case_when(etiohtlym == '1' ~ TRUE,
                          etiohtlym == '0' ~ FALSE,
                          TRUE ~ NA),
    etiohnmdar = case_when(etiohnmdar == '1' ~ TRUE,
                           etiohnmdar == '0' ~ FALSE,
                           TRUE ~ NA),
    paticond = case_when(
      site == 'Bandung' & paticond == '0' ~ 'Alive',
      site == 'Bandung' & paticond == '1' ~ 'Dead',
      site == 'Bandung' & paticond == '2' ~ 'Lost to follow up',
      site == 'Jakarta' & paticond == '1' ~ 'Alive',
      site == 'Jakarta' & paticond == '2' ~ 'Dead',
      site == 'Jakarta' & paticond == '3' ~ 'Lost to follow up',
      TRUE ~ NA_character_
      ),
    iscnsinfec = case_when(
      iscnsinfec == '1' ~ TRUE,
      iscnsinfec == '0' ~ FALSE,
      TRUE ~ NA
    ),
    is18 = case_when(
      is18 == '1' ~ TRUE,
      is18 == '0' ~ FALSE,
      TRUE ~ NA
    ),
    issigned = case_when(
      issigned == '1' ~ TRUE,
      issigned == '0' ~ FALSE,
      TRUE ~ NA
    ),
    admisdtc = ymd(admisdtc),
    admistime = case_when(
     site == 'Jakarta' ~ as.character(admistime),
     site == 'Bandung' ~ str_sub(admistime, start = 12, end = -1),
     TRUE ~ NA_character_
    ),
    admistime = hms(admistime),
    neuroinfecdtc = ymd(neuroinfecdtc),
    neuroinfectime = case_when(
      site == 'Jakarta' ~ as.character(neuroinfectime),
      site == 'Bandung' ~ str_sub(neuroinfectime, start = 12, end = -1),
      TRUE ~ NA_character_
    ),
    neuroinfectime = hms(neuroinfectime),
    fstdosend = case_when(
      site == 'Jakarta' & fstdosend == 'FALSE' ~ 'Done',
      site == 'Jakarta' & fstdosend == 'TRUE ' ~ 'Not done',
      site == 'Bandung' & fstdosend == '1' ~ 'Done',
      site == 'Bandung' & fstdosend == '0' ~ 'Not done',
      TRUE ~ NA_character_
    ),
    fstdosedtc = ymd(fstdosedtc),
    fstdosetime = case_when(
      site == 'Jakarta' ~ as.character(fstdosetime),
      site == 'Bandung' ~ str_sub(fstdosetime, start = 12, end = -1),
      TRUE ~ NA_character_
    ),
    fstdosetime = hms(fstdosetime),
    lumpuncnd = case_when(
      site == 'Jakarta' & lumpuncnd == 'FALSE' ~ 'Done',
      site == 'Jakarta' & lumpuncnd == 'TRUE ' ~ 'Not done',
      site == 'Bandung' & lumpuncnd == '1' ~ 'Done',
      site == 'Bandung' & lumpuncnd == '0' ~ 'Not done',
      TRUE ~ NA_character_
    ),
    lumpuncdtc = ymd(lumpuncdtc),
    lunpunctime = case_when(
      site == 'Jakarta' ~ as.character(lunpunctime),
      site == 'Bandung' ~ str_sub(lunpunctime, start = 12, end = -1),
      TRUE ~ NA_character_
    ),
    lunpunctime = hms(lunpunctime),
    enrolldtc = ymd(enrolldtc),
    enrolltime = case_when(
      site == 'Jakarta' ~ as.character(enrolltime),
      site == 'Bandung' ~ str_sub(enrolltime, start = 12, end = -1),
      TRUE ~ NA_character_
    ),
    enrolltime = hms(enrolltime),
    isrecrbf = case_when(
      isrecrbf == '1' ~ TRUE,
      isrecrbf == '0' ~ FALSE,
      TRUE ~ NA 
    ),
    mob = case_when(
       site == 'Jakarta' ~ as.numeric(mob),
       site == 'Bandung' ~ str_sub(dob, start = 6, end = 7) |> as.numeric(),
       TRUE ~ NA_real_
    ),
    yob = case_when(
      site == 'Jakarta' ~ as.numeric(yob),
      site == 'Bandung' ~ str_sub(dob, start = 1, end = 4) |> as.numeric(),
      TRUE ~ NA_real_
    ),
    dob = case_when(
      site == 'Jakarta' ~ as.numeric(dob),
      site == 'Bandung' ~ str_sub(dob, start = -2, end = -1) |> as.numeric(),
      TRUE ~ NA_real_
    ),
    studypl = case_when(
       studypl == '1' ~ as.numeric(studypl),
       studypl == '2' ~ as.numeric(studypl),
       studypl == '3' ~ as.numeric(studypl),
       TRUE ~ NA_real_
    ),
    refstt = case_when(
      refstt == '1' ~ as.numeric(refstt),
      refstt == '2' ~ as.numeric(refstt),
      refstt == '3' ~ as.numeric(refstt),
      TRUE ~ NA_real_
    ),
    fstsymdtc = ymd(fstsymdtc),
    fevercomp = if_else(fevercomp == '1', TRUE, FALSE),
    headcomp = if_else(headcomp == '1', TRUE, FALSE),
    vomitcomp = if_else(vomitcomp == '1', TRUE, FALSE),
    alconcomp = if_else(alconcomp == '1', TRUE, FALSE),
    lethsym = case_when(
      lethsym == '1' ~ as.numeric(lethsym),
      lethsym == '0' ~ as.numeric(lethsym),
      lethsym %in% c('8', '9') ~ 2,
      TRUE ~ NA_real_
    ),
    lethcomp = if_else(lethcomp == '1', TRUE, FALSE),
    lethday = case_when(
      lethday == 99999 ~ NA_real_,
      is.numeric(lethday) ~ as.numeric(lethday),
      TRUE ~ NA_real_
    ),
    bechcomp = if_else(bechcomp == '1', TRUE, FALSE),
    moabsym = case_when(
      moabsym == '1' ~ as.numeric(moabsym),
      moabsym == '0' ~ as.numeric(moabsym),
      moabsym %in% c('8', '9') ~ 2,
      TRUE ~ NA_real_
    ),
    moabcomp = if_else(moabcomp == '1', TRUE, FALSE),
    moabday = case_when(
      moabday == 99999 ~ NA_real_,
      is.numeric(moabday) ~ as.numeric(moabday),
      TRUE ~ NA_real_
    ),
    seabsym = case_when(
      seabsym == '1' ~ as.numeric(seabsym),
      seabsym == '0' ~ as.numeric(seabsym),
      seabsym %in% c('8', '9') ~ 2,
      TRUE ~ NA_real_
    ),
    seabcomp = if_else(seabcomp == '1', TRUE, FALSE),
    seabday = case_when(
      seabday == 99999 ~ NA_real_,
      is.numeric(seabday) ~ as.numeric(seabday),
      TRUE ~ NA_real_
    ),
    cranpsym = case_when(
      cranpsym == '1' ~ as.numeric(cranpsym),
      cranpsym == '0' ~ as.numeric(cranpsym),
      cranpsym %in% c('8', '9') ~ 2,
      TRUE ~ NA_real_
    ),
    cranpcomp = if_else(cranpcomp == '1', TRUE, FALSE),
    cranpday = case_when(
      cranpday == 99999 ~ NA_real_,
      is.numeric(cranpday) ~ as.numeric(cranpday),
      TRUE ~ NA_real_
    ),
    seizucomp = if_else(seizucomp == '1', TRUE, FALSE),
    seipattern = case_when(
      site == 'Jakarta' & seipattern == '1' ~ 0,
      site == 'Jakarta' & seipattern == '2' ~ 1,
      site == 'Bandung' & seipattern == '0' ~ 0,
      site == 'Bandung' & seipattern == '1' ~ 1,
      seipattern %in% c('8', '9') ~ 2,
    ),
    seiwitms = if_else(seiwitms == '1', TRUE, FALSE),
    seizufre = case_when(
      seizufre == '0' ~ 0,
      seizufre == '1' ~ 1,
      seizufre == '2' ~ 2,
      seizufre %in% c('8', '9') ~ 3,
      TRUE ~ NA_real_
    ),
    othcomp = if_else(othcomp == '1', TRUE, FALSE),
    othday = case_when(
      othday == 99999 ~ NA_real_,
      is.numeric(othday) ~ as.numeric(othday),
      TRUE ~ NA_real_
    ),
    weightlost = case_when(
      weightlost == '1' ~ as.numeric(weightlost),
      weightlost == '0' ~ as.numeric(weightlost),
      weightlost %in% c('8', '9') ~ 2,
      TRUE ~ NA_real_
    ),
    nsweat = case_when(
      nsweat == '1' ~ as.numeric(nsweat),
      nsweat == '0' ~ as.numeric(nsweat),
      nsweat %in% c('8', '9') ~ 2,
      TRUE ~ NA_real_
    ),
    bcg = case_when(
      bcg == '1' ~ as.numeric(bcg),
      bcg == '0' ~ as.numeric(bcg),
      bcg %in% c('8', '9') ~ 2,
      TRUE ~ NA_real_
    ),
    treatedtb = case_when(
      treatedtb == '1' ~ as.numeric(treatedtb),
      treatedtb == '0' ~ as.numeric(treatedtb),
      treatedtb %in% c('8', '9') ~ 2,
      TRUE ~ NA_real_
    ),
    pretb = case_when(
      pretb == '1' ~ as.numeric(pretb),
      pretb == '0' ~ as.numeric(pretb),
      pretb %in% c('8', '9') ~ 2,
      TRUE ~ NA_real_
    ),
    tbrecent = case_when(
      site == 'Jakarta' & tbrecent == '1' ~ 0,
      site == 'Jakarta' & tbrecent == '2' ~ 1,
      site == 'Jakarta' & tbrecent == '3' ~ 2,
      site == 'Jakarta' & tbrecent == '4' ~ 3,
      site == 'Bandung' & tbrecent == '0' ~ 0,
      site == 'Bandung' & tbrecent == '1' ~ 1,
      site == 'Bandung' & tbrecent == '2' ~ 2,
      site == 'Bandung' & tbrecent == '3' ~ 3,
      tbrecent %in% c('8', '9') ~ 4,
      TRUE ~ NA_real_
    ),
    tbsttrec = case_when(
      site == 'Jakarta' & tbsttrec == '1' ~ 0,
      site == 'Jakarta' & tbsttrec == '2' ~ 1,
      site == 'Jakarta' & tbsttrec == '3' ~ 2,
      site == 'Bandung' & tbsttrec == '0' ~ 0,
      site == 'Bandung' & tbsttrec == '1' ~ 1,
      site == 'Bandung' & tbsttrec == '2' ~ 2,
      TRUE ~ NA_real_
    ),
    tbsttpul = if_else(tbsttpul == '1', TRUE, FALSE),
    tbsttmen = if_else(tbsttmen == '1', TRUE, FALSE),
    tbsttoth = if_else(tbsttoth == '1', TRUE, FALSE),
    tblatent = case_when(
      tblatent == '1' ~ as.numeric(tblatent),
      tblatent == '0' ~ as.numeric(tblatent),
      tblatent %in% c('8', '9') ~ 2,
      TRUE ~ NA_real_
    ),
    tbipt = case_when(
      tbipt == '1' ~ as.numeric(tbipt),
      tbipt == '0' ~ as.numeric(tbipt),
      tbipt %in% c('8', '9') ~ 2,
      TRUE ~ NA_real_
    ),
    precns = case_when(
      precns == '1' ~ as.numeric(precns),
      precns == '0' ~ as.numeric(precns),
      precns %in% c('8', '9') ~ 2,
      TRUE ~ NA_real_
    ),
    cnsmen = if_else(cnsmen == '1', TRUE, FALSE),
    cnsenc = if_else(cnsenc == '1', TRUE, FALSE),
    cnsbra = if_else(cnsbra == '1', TRUE, FALSE),
    cnsmye = if_else(cnsmye == '1', TRUE, FALSE),
    cnsmtub = if_else(cnsmtub == '1', TRUE, FALSE),
    cnstoxo = if_else(cnstoxo == '1', TRUE, FALSE),
    cnscryp = if_else(cnscryp == '1', TRUE, FALSE),
    cnsepi = case_when(
      cnsepi == 99999 ~ NA_real_,
      is.numeric(cnsepi) ~ as.numeric(cnsepi),
      TRUE ~ NA_real_
    ),
    diabetes = case_when(
      diabetes == '1' ~ as.numeric(diabetes),
      diabetes == '0' ~ as.numeric(diabetes),
      diabetes %in% c('8', '9') ~ 2,
      TRUE ~ NA_real_
    ),
    diatherapy = case_when(
      diatherapy == '0' ~ 0,
      diatherapy == '1' ~ 1,
      diatherapy == '2' & site == 'Bandung' ~ 2,
      diatherapy == '3' & site == 'Jakarta' ~ 2,
      diatherapy == '3' & site == 'Bandung' ~ 3,
      diatherapy == '2' & site == 'Jakarta' ~ 3,
      diatherapy %in% c('8', '9') ~ 4,
      TRUE ~ NA_real_
    ),
    corticocurt = case_when(
      corticocurt == '1' ~ as.numeric(corticocurt),
      corticocurt == '0' ~ as.numeric(corticocurt),
      corticocurt %in% c('8', '9') ~ 2,
      TRUE ~ NA_real_
    ),
    piein30 = if_else(piein30 == '1', TRUE, FALSE),
    pieanimal = case_when(
      pieanimal == '1' ~ as.numeric(pieanimal),
      pieanimal == '0' ~ as.numeric(pieanimal),
      pieanimal %in% c('8', '9') ~ 2,
      TRUE ~ NA_real_
    ),
    piefreshwt = case_when(
      piefreshwt == '1' ~ as.numeric(piefreshwt),
      piefreshwt == '0' ~ as.numeric(piefreshwt),
      piefreshwt %in% c('8', '9') ~ 2,
      TRUE ~ NA_real_
    ),
    hissmoking = case_when(
      site == 'Jakarta' & hissmoking == '1' ~ 0,  
      site == 'Jakarta' & hissmoking == '2' ~ 1,  
      site == 'Jakarta' & hissmoking == '3' ~ 2, 
      site == 'Bandung' & hissmoking == '0' ~ 0,  
      site == 'Bandung' & hissmoking == '1' ~ 1,  
      site == 'Bandung' & hissmoking == '2' ~ 2, 
      TRUE ~ NA_real_
    ),
    loctemp = case_when(
      site == 'Jakarta' & loctemp == '1' ~ 0,  
      site == 'Jakarta' & loctemp == '2' ~ 1,  
      site == 'Jakarta' & loctemp == '3' ~ 2, 
      site == 'Bandung' & loctemp == '0' ~ 0,  
      site == 'Bandung' & loctemp == '1' ~ 1,  
      site == 'Bandung' & loctemp == '2' ~ 2, 
      TRUE ~ NA_real_
    ),
    respiratory = if_else(respiratory == 99999 | is.na(respiratory),
                          NA_real_, as.numeric(respiratory)),
    oxysatu = if_else(oxysatu == 99999 | is.na(oxysatu),
                      NA_real_, as.numeric(oxysatu)),
    weight = if_else(weight == 99999 | is.na(weight),
                     NA_real_, as.numeric(weight)),
    weightmth = case_when(
       site == 'Jakarta' & weightmth == '1' ~ 0,
       site == 'Jakarta' & weightmth == '2' ~ 1,
       site == 'Bandung' ~ as.numeric(weightmth),
       TRUE ~ NA_real_
    ),
    armcir = if_else(armcir == 99999 | is.na(armcir),
                     NA_real_, as.numeric(armcir)),
    height = if_else(height == 99999 | is.na(height),
                     NA_real_, as.numeric(height)),
    heightmth = case_when(
      site == 'Jakarta' & heightmth == '1' ~ 0,
      site == 'Jakarta' & heightmth == '2' ~ 1,
      site == 'Bandung' ~ as.numeric(heightmth),
      TRUE ~ NA_real_
    ),
    eyesc = if_else(eyesc >= 4, 4, as.numeric(eyesc)),
    motoric = if_else(motoric >= 6, 6, as.numeric(motoric)),
    verbal = if_else(verbal >= 5, 5, as.numeric(verbal)),
    nerve3rd = case_when(
      nerve3rd == '1' ~ as.numeric(nerve3rd),
      nerve3rd == '0' ~ as.numeric(nerve3rd),
      nerve3rd %in% c('8', '9') ~ 2,
      TRUE ~ NA_real_
    ),
    nerve4th = case_when(
      nerve4th == '1' ~ as.numeric(nerve4th),
      nerve4th == '0' ~ as.numeric(nerve4th),
      nerve4th %in% c('8', '9') ~ 2,
      TRUE ~ NA_real_
    ),
    nerve6th = case_when(
      nerve6th == '1' ~ as.numeric(nerve6th),
      nerve6th == '0' ~ as.numeric(nerve6th),
      nerve6th %in% c('8', '9') ~ 2,
      TRUE ~ NA_real_
    ),
    nerve7th = case_when(
      nerve7th == '1' ~ as.numeric(nerve7th),
      nerve7th == '0' ~ as.numeric(nerve7th),
      nerve7th %in% c('8', '9') ~ 2,
      TRUE ~ NA_real_
    ),
    nerve12th = case_when(
      nerve12th == '1' ~ as.numeric(nerve12th),
      nerve12th == '0' ~ as.numeric(nerve12th),
      nerve12th %in% c('8', '9') ~ 2,
      TRUE ~ NA_real_
    ),
    pupisz = case_when(
      site == 'Jakarta' & pupisz == '1' ~ 0,
      site == 'Jakarta' & pupisz == '2' ~ 1,
      site == 'Bandung' ~ as.numeric(pupisz),
      TRUE ~ NA_real_
    ),
    pupiref = case_when(
      site == 'Jakarta' & pupiref == '1' ~ 0,
      site == 'Jakarta' & pupiref == '2' ~ 1,
      site == 'Jakarta' & pupiref == '3' ~ 2,
      site == 'Bandung' ~ as.numeric(pupiref),
      pupiref == '8' ~ 3,
      TRUE ~ NA_real_
    ),
    urinary = case_when(
      urinary == '1' ~ as.numeric(urinary),
      urinary == '0' ~ as.numeric(urinary),
      urinary %in% c('8', '9') ~ 2,
      TRUE ~ NA_real_
    ),
    gasbleed = case_when(
      gasbleed == '1' ~ as.numeric(gasbleed),
      gasbleed == '0' ~ as.numeric(gasbleed),
      gasbleed %in% c('8', '9') ~ 2,
      TRUE ~ NA_real_
    ),
    inidiamen = if_else(inidiamen == 1, TRUE, FALSE),
    inidiaence = if_else(inidiaence == 1, TRUE, FALSE),
    inidiamye = if_else(inidiamye == 1, TRUE, FALSE),
    inidiabrain = if_else(inidiabrain == 1, TRUE, FALSE),
    inidiaenc = if_else(inidiaenc == 1, TRUE, FALSE),
    suetibac = if_else(suetibac == 1, TRUE, FALSE),
    suetiviral = if_else(suetiviral == 1, TRUE, FALSE),
    suetitoxo = if_else(suetitoxo == 1, TRUE, FALSE),
    suetiauto = if_else(suetiauto == 1, TRUE, FALSE),
    sueticryp = if_else(sueticryp == 1, TRUE, FALSE),
    suetimtube = if_else(suetimtube == 1, TRUE, FALSE),
    suetiunk = if_else(suetiunk == 1, TRUE, FALSE),
    suetiunk = if_else(suetiunk == 1, TRUE, FALSE),
    cnsinfec = case_when(
      site == 'Jakarta' & cnsinfec == '1' ~ 0,
      site == 'Jakarta' & cnsinfec == '2' ~ 1,
      site == 'Jakarta' & cnsinfec == '3' ~ 2,
      site == 'Jakarta' & cnsinfec == '4' ~ 3,
      site == 'Bandung' ~ as.numeric(cnsinfec),
      TRUE ~ NA_real_
    ),
    othonset = if_else(othonset == 99999 | is.na(othonset),
                       NA_real_, as.numeric(othonset)),
    onsetstt = case_when(
      site == 'Jakarta' & onsetstt == '1' ~ 0,
      site == 'Jakarta' & onsetstt == '2' ~ 1,
      site == 'Bandung' ~ as.numeric(onsetstt),
      TRUE ~ NA_real_
    ),
    hivresult = case_when(
      hivresult == '1' ~ as.numeric(hivresult),
      hivresult == '0' ~ as.numeric(hivresult),
      hivresult %in% c('2', '9') ~ 2,
      TRUE ~ NA_real_
    ),
    xray = case_when(
      site == 'Jakarta' & xray == '1' ~ 0,
      site == 'Jakarta' & xray == '2' ~ 1,
      site == 'Jakarta' & xray == '3' ~ 2,
      site == 'Bandung' ~ as.numeric(xray),
      TRUE ~ NA_real_
    ),
    tbdrug = case_when(
      site == 'Jakarta' & tbdrug == '1' ~ 0,
      site == 'Jakarta' & tbdrug == '2' ~ 1,
      site == 'Bandung'  ~ as.numeric(tbdrug),
      TRUE ~ NA_real_
    ),
    tbdrugdtc = ymd(tbdrugdtc),
    tbdrugstt = case_when(
      site == 'Jakarta' & tbdrugstt == '1' ~ 0,
      site == 'Jakarta' & tbdrugstt == '2' ~ 1,
      site == 'Bandung'  ~ as.numeric(tbdrugstt),
      TRUE ~ NA_real_
    ),
    levof = case_when(
      site == 'Jakarta' & levof == '1' ~ 0,
      site == 'Jakarta' & levof == '2' ~ 1,
      site == 'Bandung'  ~ as.numeric(levof),
      TRUE ~ NA_real_
    ),
    levofdtc = ymd(levofdtc),
    levofstt = case_when(
      site == 'Jakarta' & levofstt == '1' ~ 0,
      site == 'Jakarta' & levofstt == '2' ~ 1,
      site == 'Bandung' ~ as.numeric(levofstt),
      TRUE ~ NA_real_
    ),
    moxif = case_when(
      site == 'Jakarta' & moxif == '1' ~ 0,
      site == 'Jakarta' & moxif == '2' ~ 1,
      site == 'Bandung'  ~ as.numeric(moxif),
      TRUE ~ NA_real_
    ),
    moxifdtc = ymd(moxifdtc),
    moxifstt = case_when(
      site == 'Jakarta' & moxifstt == '1' ~ 0,
      site == 'Jakarta' & moxifstt == '2' ~ 1,
      site == 'Bandung' ~ as.numeric(moxifstt),
      TRUE ~ NA_real_
    ),
    cotrimo = case_when(
      site == 'Jakarta' & cotrimo == '1' ~ 0,
      site == 'Jakarta' & cotrimo == '2' ~ 1,
      site == 'Bandung' ~ as.numeric(cotrimo),
      TRUE ~ NA_real_
    ),
    cotrimodtc = ymd(cotrimodtc),
    cotrimostt = case_when(
      site == 'Jakarta' & cotrimostt == '1' ~ 0,
      site == 'Jakarta' & cotrimostt == '2' ~ 1,
      site == 'Bandung' ~ as.numeric(cotrimostt),
      TRUE ~ NA_real_
    ),
    metroni = case_when(
      site == 'Jakarta' & metroni == '1' ~ 0,
      site == 'Jakarta' & metroni == '2' ~ 1,
      site == 'Bandung' ~ as.numeric(metroni),
      TRUE ~ NA_real_
    ),
    metronidtc = ymd(metronidtc),
    metronistt = case_when(
      site == 'Jakarta' & metronistt == '1' ~ 0,
      site == 'Jakarta' & metronistt == '2' ~ 1,
      site == 'Bandung' ~ as.numeric(metronistt),
      TRUE ~ NA_real_
    ),
    pyrime = case_when(
      site == 'Jakarta' & pyrime == '1' ~ 0,
      site == 'Jakarta' & pyrime == '2' ~ 1,
      site == 'Bandung' ~ as.numeric(pyrime),
      TRUE ~ NA_real_
    ),
    pyrimedtc = ymd(pyrimedtc),
    pyrimestt = case_when(
      site == 'Jakarta' & pyrimestt == '1' ~ 0,
      site == 'Jakarta' & pyrimestt == '2' ~ 1,
      site == 'Bandung' ~ as.numeric(pyrimestt),
      TRUE ~ NA_real_
    ),
    
    clinda = case_when(
      site == 'Jakarta' & clinda == '1' ~ 0,
      site == 'Jakarta' & clinda == '2' ~ 1,
      site == 'Bandung' ~ as.numeric(clinda),
      TRUE ~ NA_real_
    ),
    
    ### This section may not be reproducible in additional dataset, check again!
    clindadtc = clindadtc0,
    clindastt0 = clindastt0,
    ###
    
    fluco = case_when(
      site == 'Jakarta' & fluco == '1' ~ 0,
      site == 'Jakarta' & fluco == '2' ~ 1,
      site == 'Bandung' ~ as.numeric(fluco),
      TRUE ~ NA_real_
    ),
    flucodtc = ymd(flucodtc),
    flucostt = case_when(
      site == 'Jakarta' & flucostt == '1' ~ 0,
      site == 'Jakarta' & flucostt == '2' ~ 1,
      site == 'Bandung' ~ as.numeric(flucostt),
      TRUE ~ NA_real_
    ), 
    
  ) |>
  
  # Make sure all categories are present despite missingness
  mutate(
    flucostt = factor(flucostt,
                      levels = c(0, 1),
                      labels = c('Initiated', 'Continued')),
    fluco = factor(fluco,
                   levels = c(0, 1),
                   labels = c('Started before LP', 'Started after LP')),
    clindastt = factor(clindastt,
                       levels = c(0, 1),
                       labels = c('Initiated', 'Continued')),
    clinda = factor(clinda,
                    levels = c(0, 1),
                    labels = c('Started before LP', 'Started after LP')),
    pyrimestt = factor(pyrimestt,
                       levels = c(0, 1),
                       labels = c('Initiated', 'Continued')),
    pyrime = factor(pyrime,
                    levels = c(0, 1),
                    labels = c('Started before LP', 'Started after LP')),
    metronistt = factor(metronistt,
                        levels = c(0, 1),
                        labels = c('Initiated', 'Continued')),
    metroni = factor(metroni,
                     levels = c(0, 1),
                     labels = c('Started before LP', 'Started after LP')),
    cotrimostt = factor(cotrimostt,
                        levels = c(0, 1),
                        labels = c('Initiated', 'Continued')),
    cotrimo = factor(cotrimo,
                     levels = c(0, 1),
                     labels = c('Started before LP', 'Started after LP')),
    moxifstt = factor(moxifstt,
                      levels = c(0, 1),
                      labels = c('Initiated', 'Continued')),
    moxif = factor(moxif,
                   levels = c(0, 1),
                   labels = c('Started before LP', 'Started after LP')),
    levofstt = factor(levofstt,
                      levels = c(0, 1),
                      labels = c('Initiated', 'Continued')),
    levof = factor(levof,
                   levels = c(0, 1),
                   labels = c('Started before LP', 'Started after LP')),
    tbdrugstt = factor(tbdrugstt,
                       levels = c(0, 1),
                       labels = c('Initiated', 'Continued')),
    tbdrug = factor(tbdrug,
                    levels = c(0, 1),
                    labels = c('Started before LP', 'Started after LP')),
    xray = factor(xray,
                  levels = c(0, 1, 2),
                  labels = c('Normal',
                             'Compatible with TB',
                             'Abnormal but not necessarily TB')),
    extraclues = factor(extraclues,
                        levels = c(0, 1),
                        labels = c('No', 'Yes')),
    hivresult = factor(hivresult,
                       levels = c(0, 1, 2),
                       labels = c('Negative', 'Positive', 'Not done')),
    csfabnor = factor(csfabnor,
                      levels = c(0, 1, 2),
                      labels = c('Negative', 'Positive', 'Not done')),
    onsetstt = factor(onsetstt,
                      levels = c(0, 1), # Ambiguous 10-day cutoff
                      labels = c('Acute', 'Subacute')), 
    cnsinfec = factor(cnsinfec,
                      levels = c(0, 1, 2, 3),
                      labels = c('Confirmed', 'Probable',
                                 'Possible', 'Unlikely')),
    gradespec = factor(gradespec,
                       levels = c(1, 2, 3),
                       labels = c(
                         'Grade 1: GCS 15, no neurological deficiency',
                         'Grade 2: GCS 11-14, or CGS 15 + neurological deficit
                          (new focal neurological signs in this episode)',
                         'Grade 3: GCS ≤ 10'
                       )),
    monopare = factor(monopare,
                      levels = c('No', 'Yes', 'Unknown'),
                      labels = c('No', 'Yes', 'Unknown')),
    tetrapare = factor(tetrapare,
                       levels = c('No', 'Yes', 'Unknown'),
                       labels = c('No', 'Yes', 'Unknown')),
    parapare = factor(parapare,
                      levels = c('No', 'Yes', 'Unknown'),
                      labels = c('No', 'Yes', 'Unknown')),
    hemipare = factor(hemipare,
                      levels = c('No', 'Yes', 'Unknown'),
                      labels = c('No', 'Yes', 'Unknown')),
    motordef = factor(motordef,
                      levels = c('No', 'Yes', 'Unknown'),
                      labels = c('No', 'Yes', 'Unknown')),
    neckstiff = factor(neckstiff,
                       levels = c('No', 'Yes', 'Unknown'),
                       labels = c('No', 'Yes', 'Unknown')),
    papille = factor(papille,
                     levels = c('No', 'Yes', 'Unknown'),
                     labels = c('No', 'Yes', 'Unknown')),
    palsy = factor(palsy,
                   levels = c('No', 'Yes', 'Unknown'),
                   labels = c('No', 'Yes', 'Unknown')),
    cough = factor(cough,
                   levels = c('None', '<2 weeks', '>2 weeks', 'Unknown'),
                   labels = c('None', '<2 weeks', '>2 weeks', 'Unknown')),
    seizusym = factor(seizusym,
                      levels = c('No', 'Yes', 'Unknown'),
                      labels = c('No', 'Yes', 'Unknown')),
    bechsym = factor(bechsym,
                     levels = c('No', 'Yes', 'Unknown'),
                     labels = c('No', 'Yes', 'Unknown')),
    vomitsym = factor(vomitsym,
                      levels = c('No', 'Yes', 'Unknown'),
                      labels = c('No', 'Yes', 'Unknown')),
    headsym = factor(headsym,
                     levels = c('No', 'Yes', 'Unknown'),
                     labels = c('No', 'Yes', 'Unknown')),
    hivvalue = factor(hivvalue,
                      levels = c('No', 'Yes', 'Unknown'),
                      labels = c('No', 'Yes', 'Unknown')),
    gasbleed = factor(gasbleed,
                      levels = c(0, 1, 2),
                      labels = c('No', 'Yes', 'Unknown')),  
    urinary = factor(urinary,
                     levels = c(0, 1, 2),
                     labels = c('No', 'Yes', 'Unknown')),  
    pupiref = factor(pupiref,
                     levels = c(0, 1, 2, 3),
                     labels = c('Normal', 'Sluggish', 'Absent', 'Unknown')),
    pupisz = factor(pupisz,
                    levels = c(0, 1),
                    labels = c('Normal', 'Anisocoria')),
    nerve12th = factor(nerve12th,
                       levels = c(0, 1, 2),
                       labels = c('No', 'Yes', 'Unknown')),  
    nerve7th = factor(nerve7th,
                      levels = c(0, 1, 2),
                      labels = c('No', 'Yes', 'Unknown')),  
    nerve6th = factor(nerve6th,
                      levels = c(0, 1, 2),
                      labels = c('No', 'Yes', 'Unknown')),
    nerve4th = factor(nerve4th,
                      levels = c(0, 1, 2),
                      labels = c('No', 'Yes', 'Unknown')),
    nerve3rd = factor(nerve3rd,
                         levels = c(0, 1, 2),
                         labels = c('No', 'Yes', 'Unknown')),
    heightmth = factor(heightmth,
                       levels = c(0, 1),
                       labels = c('Measured', 'Estimated')),
    armcirmea = factor(armcirmea,
                       levels = c(0, 1),
                       labels = c('Measured', 'Estimated')),
    weightmth = factor(weightmth,
                       levels = c(0, 1),
                       labels = c('Measured', 'Estimated')),
    loctemp = factor(loctemp,
                     levels = c(0, 1, 2),
                     labels = c('Axillary', 'Tympanic', 'Forehead')),
    hissmoking = factor(hissmoking,
                        levels = c(0, 1, 2),
                        labels = c('Currently', 'Previously', 'Never')),
    piefreshwt = factor(piefreshwt,
                        levels = c(0, 1, 2),
                        labels = c('No', 'Yes', 'Unknown')),
    pieanimal = factor(pieanimal,
                       levels = c(0, 1, 2),
                       labels = c('No', 'Yes', 'Unknown')),
    corticodur = factor(corticodur,
                        levels = c(1, 2, 3),
                        labels = c('<1 week',
                                   '1 week-1 month',
                                   '>1 month')),
    corticocurt = factor(corticocurt,
                         levels = c(0, 1, 2),
                         labels = c('No', 'Yes', 'Unknown')),
    diatherapy = factor(diatherapy,
                        levels = c(0, 1, 2, 3, 4),
                        labels = c('None',
                                   'Insulin',
                                   'Metformin',
                                   'Other',
                                   'Unknown')),
    diabetes = factor(diabetes,
                      levels = c(0, 1, 2),
                      labels = c('No', 'Yes', 'Unknown')),
    cnsfre = factor(cnsfre,
                    levels = c(1, 2),
                    labels = c('Once', 'More than once')),
    precns = factor(precns,
                    levels = c(0, 1, 2),
                    labels = c('No', 'Yes', 'Unknown')),
    tbipt = factor(tbipt,
                   levels = c(0, 1, 2),
                   labels = c('No', 'Yes', 'Unknown')),
    tblatent = factor(tblatent,
                      levels = c(0, 1, 2),
                      labels = c('No', 'Yes', 'Unknown')),
    tbsttrec = factor(tbsttrec,
                      levels = c(0, 1, 2),
                      labels = c('Ongoing', 'Completed', 'Interrupted')),
    tbrecent = factor(tbrecent,
                      levels = c(0, 1, 2, 3, 4),
                      labels = c('<1 year',
                                 '1-3 years',
                                 '3-10 years',
                                 '>10 years',
                                 'Unknown')),
    tbfre = factor(tbfre,
                   levels = c(1, 2),
                   labels = c('Once', 'More than once')),
    pretb = factor(pretb,
                   levels = c(0, 1, 2),
                   labels = c('No', 'Yes', 'Unknown')),
    timettb = factor(timettb,
                     levels = c(1, 2),
                     labels = c('<=1 year', '>1 year')),
    treatedtb = factor(treatedtb,
                       levels = c(0, 1, 2),
                       labels = c('No', 'Yes', 'Unknown')),
    bcg = factor(bcg,
                 levels = c(0, 1, 2),
                 labels = c('No', 'Yes', 'Unknown')),
    nsweat = factor(nsweat,
                    levels = c(0, 1, 2),
                    labels = c('No', 'Yes', 'Unknown')),
    weightlost = factor(weightlost,
                        levels = c(0, 1, 2),
                        labels = c('No', 'Yes', 'Unknown')),
    seizufre = factor(seizufre,
                      levels = c(0, 1, 2, 3),
                      labels = c('No', 'Once', 'Repeated', 'Unknown')),
    seipattern = factor(seipattern,
                        levels = c(0, 1, 2),
                        labels = c('Focal', 'General', 'Unknown')),
    cranpsym = factor(cranpsym,
                      levels = c(0, 1, 2),
                      labels = c('No', 'Yes', 'Unknown')),
    seabsym = factor(seabsym,
                     levels = c(0, 1, 2),
                     labels = c('No', 'Yes', 'Unknown')),
    moabsym = factor(moabsym,
                     levels = c(0, 1, 2),
                     labels = c('No', 'Yes', 'Unknown')),
    lethsym = factor(lethsym,
                     levels = c(0, 1, 2),
                     labels = c('No', 'Yes', 'Unknown')),
    refstt = factor(refstt,
                    levels = c(1, 2, 3),
                    labels = c('Self-referral',
                               'Hospital referral',
                               'Primary health care')),
    studypl = factor(studypl,
                     levels = c(1, 2, 3),
                     labels = c('ER', 'Ward', 'Outpatient')),
    fstdosend = factor(fstdosend,
                       levels = c('Done', 'Not done'),
                       labels = c('Done', 'Not done')),
    lumpuncnd = factor(lumpuncnd,
                       levels = c('Done', 'Not done'),
                       labels = c('Done', 'Not done')),
    sex = factor(sex,
                 levels = c('Female', 'Male'),
                 labels = c('Female', 'Male')),
    hivvalue = factor(hivvalue,
                      levels = c('Positive', 'Negative', 'Not done'),
                      labels = c('Positive', 'Negative', 'Not done')),
    antiigg_res = factor(antiigg_res,
                         levels = c('Positive', 'Negative', 'Not done'),
                         labels = c('Positive', 'Negative', 'Not done')),
    hivstt = factor(hivstt,
                    levels = c('Positive', 'Negative', 'Not done'),
                    labels = c('Positive', 'Negative', 'Not done')),
    crag1 = factor(crag1,
                   levels = c('Positive', 'Negative', 'Not done'),
                   labels = c('Positive', 'Negative', 'Not done')),
    crag2 = factor(crag2,
                   levels = c('Positive', 'Negative', 'Not done'),
                   labels = c('Positive', 'Negative', 'Not done')),
    xpert1 = factor(xpert1,
                    levels = c('Positive', 'Negative', 'Not done'),
                    labels = c('Positive', 'Negative', 'Not done')),
    xpert2 = factor(xpert2,
                    levels = c('Positive', 'Negative', 'Not done'),
                    labels = c('Positive', 'Negative', 'Not done')),
    xpertrif1 = factor(xpertrif1,
                       levels = c('RIF-resistant', 'RIF-sensitive'),
                       labels = c('RIF-resistant', 'RIF-sensitive')),
    xpertrif2 = factor(xpertrif2,
                       levels = c('RIF-resistant', 'RIF-sensitive'),
                       labels = c('RIF-resistant', 'RIF-sensitive')),
    csfcmv1 = factor(csfcmv1,
                     levels = c('Positive', 'Negative', 'Not done'),
                     labels = c('Positive', 'Negative', 'Not done')),
    csfcmv2 = factor(csfcmv2,
                     levels = c('Positive', 'Negative', 'Not done'),
                     labels = c('Positive', 'Negative', 'Not done')),
    csfhsv1 = factor(csfhsv1,
                     levels = c('Positive', 'Negative', 'Not done'),
                     labels = c('Positive', 'Negative', 'Not done')),
    csfhsv2 = factor(csfhsv2,
                     levels = c('Positive', 'Negative', 'Not done'),
                     labels = c('Positive', 'Negative', 'Not done')),
    csfebv1 = factor(csfebv1,
                     levels = c('Positive', 'Negative', 'Not done'),
                     labels = c('Positive', 'Negative', 'Not done')),
    csfebv2 = factor(csfebv2,
                     levels = c('Positive', 'Negative', 'Not done'),
                     labels = c('Positive', 'Negative', 'Not done')),
    csfvzv1 = factor(csfvzv1,
                     levels = c('Positive', 'Negative', 'Not done'),
                     labels = c('Positive', 'Negative', 'Not done')),
    csfvzv2 = factor(csfvzv2,
                     levels = c('Positive', 'Negative', 'Not done'),
                     labels = c('Positive', 'Negative', 'Not done')),
    csfvdrl1 = factor(csfvdrl1,
                      levels = c('Positive', 'Negative', 'Not done'),
                      labels = c('Positive', 'Negative', 'Not done')),
    csfvdrl2 = factor(csfvdrl2,
                      levels = c('Positive', 'Negative', 'Not done'),
                      labels = c('Positive', 'Negative', 'Not done')),
    csftpha1 = factor(csftpha1,
                      levels = c('Positive', 'Negative', 'Not done'),
                      labels = c('Positive', 'Negative', 'Not done')),
    csftpha2 = factor(csftpha2,
                      levels = c('Positive', 'Negative', 'Not done'),
                      labels = c('Positive', 'Negative', 'Not done')),
    outcome = factor(outcome,
                     levels = c('Alive', 'Dead', 'Discharged',
                                'Self-discharged',
                                'Referred to another hospital',
                                'Hospitalised'),
                     labels = c('Alive', 'Dead', 'Discharged',
                                'Self-discharged',
                                'Referred to another hospital',
                                'Hospitalised')),
    etmtustt = factor(etmtustt,
                      levels = c('Definite', 'Probable', 'Possible'),
                      labels = c('Definite', 'Probable', 'Possible')),
    etitoxostt = factor(etitoxostt,
                        levels = c('Definite', 'Probable', 'Possible'),
                        labels = c('Definite', 'Probable', 'Possible')),
    eticrypstt = factor(eticrypstt,
                        levels = c('Definite', 'Probable', 'Possible'),
                        labels = c('Definite', 'Probable', 'Possible')),
    etibacstt = factor(etibacstt,
                       levels = c('Definite', 'Probable', 'Possible'),
                       labels = c('Definite', 'Probable', 'Possible')),
    etivencestt = factor(etivencestt,
                         levels = c('Definite', 'Probable', 'Possible'),
                         labels = c('Definite', 'Probable', 'Possible')),
    paticond = factor(paticond,
                      levels = c('Alive', 'Dead', 'Lost to follow up'),
                      labels = c('Alive', 'Dead', 'Lost to follow up'))) |>
  
  # Derived variables
  mutate(comppare = case_when(hemipare == 'Yes'|
                              parapare == 'Yes' |
                              tetrapare == 'Yes' |
                              monopare == 'Yes' ~ TRUE,
                              hemipare == 'No'&
                              parapare == 'No' &
                              tetrapare == 'No' &
                              monopare == 'No' ~ FALSE,
                              TRUE ~ NA)) |>
  
  # Include or exclude observed, cleaned variables
  mutate(
    hivstt = case_when(
      site == 'Jakarta' ~ hivstt,
      site == 'Bandung' ~ hivvalue,
      TRUE ~ NA_integer_
    )
  )
  
# Label variables
var_label(ibis) <- list(
  site = 'Study site',
  siteid = 'Study site ID',
  subjid = 'Unique patient ID',
  age = 'Age (years)',
  sex = 'Biological sex',
  symdays = 'Duration of symptoms (days)',
  feversym = 'Fever',
  feverday = 'Duration of fever (days)',
  headsym = 'Headache',
  headday = 'Duration of headache (days)',
  vomitsym = 'Vomiting',
  vomitday = 'Duration of vomiting (days)',
  alconsym = 'Altered conciousness',
  alconday = 'Duration of altered conciousness (days)',
  bechsym = 'Behavioural change',
  bechday = 'Duration of behavioural change (days)',
  seizusym = 'Seizure',
  seizuonset = 'Onset prior to baseline (days)',
  cough = 'Coughing',
  htemp = 'Highest recorded temperature at baseline (celcius)',
  gcs = 'Total GCS at baseline',
  palsy = 'Cranial nerve palsy',
  papille = 'Papilledema',
  neckstiff = 'Neck stiffness',
  motordef = 'Motor deficits',
  hemipare = 'Hemiparesis',
  parapare = 'Paraparesis',
  tetrapare = 'Tetraparesis',
  monopare = 'Monoparesis',
  hemovalue = 'Haemoglobin level (g/dL)',
  wcellcvalue = 'White blood cell count (in 1000 cells/μL)',
  platevalue = 'Platelet count (in 1000 cells/μL)',
  hivvalue = 'HIV test',
  cd4value = 'CD4 cell count (cells/L)',
  antiigg_res = 'Antitoxoplasma IgG',
  hivstt = 'HIV status',
  whcellc1 = 'Total white cell count (cells/μL), 1',
  whcellc2 = 'Total white cell count (cells/μL), 2',
  polycellc1 = 'Polymorphonuclear cell count (cells/μL), 1',
  polycellc2 = 'Polymorphonuclear cell count (cells/μL), 2',
  monocellc1 = 'Mononuclear cell count (cells/μL), 1',
  monocellc2 = 'Mononuclear cell count (cells/μL), 2',
  protein1 = 'Total protein (mg/dL), 1',
  protein2 = 'Total protein (mg/dL), 2',
  pblglucose1 = 'Paired blood glucose (mg/dL), 1',
  pblglucose2 = 'Paired blood glucose (mg/dL), 2',
  ratio_glucose1 = 'Glucose ratio, 1',
  ratio_glucose2 = 'Glucose ratio, 2',
  crag1 = 'Cryptococcal antigen test, 1',
  crag2 = 'Cryptococcal antigen test, 2',
  xpert1 = 'Gene Xpert, 1',
  xpert2 = 'Gene Xpert, 2',
  xpertrif1 = 'RIF resistance, 1',
  xpertrif2 = 'RIF resistance, 2',
  csfcmv1 = 'CSF PCR for CMV, 1',
  csfcmv2 = 'CSF PCR for CMV, 2',
  csfhsv1 = 'CSF PCR for HSV, 1',
  csfhsv2 = 'CSF PCR for HSV, 2',
  csfebv1 = 'CSF PCR for EBV, 1',
  csfebv2 = 'CSF PCR for EBV, 2',
  csfvzv1 = 'CSF PCR for VZV, 1',
  csfvzv2 = 'CSF PCR for VZV, 2',
  csfvdrl1 = 'CSF PCR for VDRL, 1',
  csfvdrl2 = 'CSF PCR for VDRL, 2',
  csftpha1 = 'CSF PCR for TPHA, 1',
  csftpha2 = 'CSF PCR for TPHA, 2',
  xraynm = 'Chest X-ray: Normal',
  xrayinf = 'Chest X-ray: Infiltrates',
  xraymili = 'Chest X-ray: Miliary',
  xraycav = 'Chest X-ray: Cavities',
  xray_ores = 'Chest X-ray: Other',
  bihernia1 = 'Herniation, 1',
  bihernia2 = 'Herniation, 2',
  bihernia3 = 'Herniation, 3',
  bienceph1 = 'Encephalitis, 1',
  bienceph2 = 'Encephalitis, 2',
  bienceph3 = 'Encephalitis, 3',
  staydur = 'Duration of stay (days)',
  outcome = 'Outcome',
  nonneuspec = 'Non-neuroinfection case, specified',
  etiomtuber = 'M. tuberculosis',
  etmtustt = 'M. tuberculosis status',
  etitoxoenc = 'Toxoplasma encephalitis',
  etitoxostt = 'Toxoplasma encephalitis status',
  eticryp = 'Cryptococcal meningitis',
  eticrypstt = 'Cryptococcal meningitis status',
  etibac = 'Bacterial meningitis',
  etibacstt = 'Bacterial meningitis status',
  etivence = 'Viral encephalitis',
  etivencestt = 'Viral encephalitis status',
  etiothba = 'Brain abcess',
  etiothmuco = 'Mucormycosis',
  etiothbm = 'Bacterial meningitis',
  etiothneu = 'Neurosyphilis',
  etiohtlym = 'Lymphoma',
  etiohnmdar = 'NMDAR encephalitis',
  etioothspec = 'Other aetiology',
  paticond = "Patient's condition",
  comppare = 'Presence of any paresis',
  initial = "Patient's initial"
)

# Exclude variables
ibis <- ibis |>
  select(-c(hivvalue, clindastt)) |> 
  rename(clindastt = clindastt0)

# Take a look at the cleaned dataset
glimpse(ibis)

# Save --------------------------------------------------------------------

ibis |> write_rds(here('0-data', 'ibis_all-cleaned.rds')) # R
ibis |> write_sav(here('0-data', 'ibis_all-cleaned.sav')) # SPSS
ibis |> write_dta(here('0-data', 'ibis_all-cleaned.dta')) # Stata

# Appendix ----------------------------------------------------------------

sessioninfo::platform_info()



















