
# Preamble ----------------------------------------------------------------

# Code author  : Ihsan Fadilah
# Email        : ifadilah@eocru.org
# Last updated : Early February 2022
# Project      : Indonesia Brain Infection Study

# This script provides reproducible code for cleaning the data. It does not have
# the dependency inherent in the script file `01-import-merge.R`. However, this
# code depends on the assumption that the format of data collection remains 
# the same throughout the project. For instance, `feversym` at the Jakarta site
# uses '9' to represent missingness and no new categories of variables are
# introduced to this dataset afterwards. If so, these new categories would be
# mistakenly read as missing data.

# Setup -------------------------------------------------------------------

library(tidyverse)  # Tidy code
library(labelled)   # Label variables
library(here)       # Navigate files
library(lubridate)  # Date-time variable
library(haven)      # Write datasets in SPSS format

# Load --------------------------------------------------------------------

ibis_raw <- here('0-data', 'ibis_all-merged.rds') |> read_rds()
glimpse(ibis_raw) # Take a look at the raw data (after merging)

# Clean -------------------------------------------------------------------

ibis <- ibis_raw |>

  # Redefine categories or values
  mutate(
    sex = case_when(site == 'Jakarta' & sex == 'F' ~ 'Female',
                    site == 'Jakarta' & sex == 'M' ~ 'Male',
                    site == 'Bandung' & sex == '0' ~ 'Female',
                    site == 'Bandung' & sex == '1' ~ 'Male',
                    TRUE ~ NA_character_),
    symdays = if_else(is.na(symdays) | symdays == 99999, NA_real_, symdays),
    feversym = case_when(feversym == '1' ~ TRUE,
                         feversym == '0' ~ FALSE,
                         site == 'Jakarta' & feversym == '9' ~ NA,
                         site == 'Bandung' & feversym == '8' ~ NA,
                         TRUE ~ NA),
    feverday = if_else(is.na(feverday) | feverday == 99999, NA_real_, feverday),
    headsym = case_when(headsym == '1' ~ TRUE,
                        headsym == '0' ~ FALSE,
                        site == 'Jakarta' & headsym == '9' ~ NA,
                        site == 'Bandung' & headsym == '8' ~ NA,
                        TRUE ~ NA),
    headday = if_else(is.na(headday) | headday == 99999, NA_real_, headday),
    vomitsym = case_when(vomitsym == '1' ~ TRUE,
                         vomitsym == '0' ~ FALSE,
                         site == 'Jakarta' & vomitsym == '9' ~ NA,
                         site == 'Bandung' & vomitsym == '8' ~ NA,
                         TRUE ~ NA),
    vomitday = if_else(is.na(vomitday) | vomitday == 99999, NA_real_, vomitday),
    alconsym = case_when(alconsym == '1' ~ TRUE,
                         alconsym == '0' ~ FALSE,
                         site == 'Jakarta' & alconsym == '9' ~ NA,
                         site == 'Bandung' & alconsym == '8' ~ NA,
                         TRUE ~ NA),
    alconday = if_else(is.na(alconday) | alconday == 99999, NA_real_, alconday),
    bechsym = case_when(bechsym == '1' ~ TRUE,
                        bechsym == '0' ~ FALSE,
                        site == 'Jakarta' & bechsym == '9' ~ NA,
                        site == 'Bandung' & bechsym == '8' ~ NA,
                        TRUE ~ NA),
    bechday = if_else(is.na(bechday) | bechday == 99999, NA_real_, bechday),
    seizusym = case_when(seizusym == '1' ~ TRUE,
                         seizusym == '0' ~ FALSE,
                         site == 'Jakarta' & seizusym == '9' ~ NA,
                         site == 'Bandung' & seizusym == '8' ~ NA,
                         TRUE ~ NA),
    seizuonset = if_else(is.na(seizuonset) | seizuonset == 99999,
                         NA_real_, seizuonset),
    cough = case_when(cough == '0' ~ 'None',
                      cough == '1' ~ '<2 weeks',
                      cough == '2' ~ '>2 weeks',
                      site == 'Jakarta' & cough == '9' ~ NA_character_,
                      site == 'Bandung' & cough == '8' ~ NA_character_,
                      TRUE ~ NA_character_),
    cough = ordered(cough, levels = c('None', '<2 weeks', '>2 weeks')),
    htemp = if_else(is.na(htemp) | htemp == 99999, NA_real_, htemp),
    gcs = if_else(is.na(gcs) | gcs == 99999, NA_real_, gcs),
    palsy = case_when(palsy == '1' ~ TRUE,
                      palsy == '0' ~ FALSE,
                      site == 'Jakarta' & palsy == '9' ~ NA,
                      site == 'Bandung' & palsy == '8' ~ NA,
                      TRUE ~ NA),
    papille = case_when(papille == '1' ~ TRUE,
                        papille == '0' ~ FALSE,
                        site == 'Jakarta' & papille == '9' ~ NA,
                        site == 'Bandung' & papille == '8' ~ NA,
                        TRUE ~ NA),
    neckstiff = case_when(neckstiff == '1' ~ TRUE,
                          neckstiff == '0' ~ FALSE,
                          site == 'Jakarta' & neckstiff == '9' ~ NA,
                          site == 'Bandung' & neckstiff == '8' ~ NA,
                          TRUE ~ NA),
    motordef = case_when(motordef == '1' ~ TRUE,
                         motordef == '0' ~ FALSE,
                         site == 'Jakarta' & motordef == '9' ~ NA,
                         site == 'Bandung' & motordef == '8' ~ NA,
                         TRUE ~ NA),
    hemipare = case_when(hemipare == '1' ~ TRUE,
                         hemipare == '0' ~ FALSE,
                         site == 'Jakarta' & hemipare == '9' ~ NA,
                         site == 'Bandung' & hemipare == '8' ~ NA,
                         TRUE ~ NA),
    parapare = case_when(parapare == '1' ~ TRUE,
                         parapare == '0' ~ FALSE,
                         site == 'Jakarta' & parapare == '9' ~ NA,
                         site == 'Bandung' & parapare == '8' ~ NA,
                         TRUE ~ NA),
    tetrapare = case_when(tetrapare == '1' ~ TRUE,
                          tetrapare == '0' ~ FALSE,
                         site == 'Jakarta' & tetrapare == '9' ~ NA,
                         site == 'Bandung' & tetrapare == '8' ~ NA,
                         TRUE ~ NA),
    monopare = case_when(monopare == '1' ~ TRUE,
                         monopare == '0' ~ FALSE,
                         site == 'Jakarta' & monopare == '9' ~ NA,
                         site == 'Bandung' & monopare == '8' ~ NA,
                         TRUE ~ NA),
    hemovalue = if_else(is.na(hemovalue) | hemovalue == 99999, 
                        NA_real_, hemovalue),
    wcellcvalue = if_else(is.na(wcellcvalue) | wcellcvalue == 99999, 
                          NA_real_, wcellcvalue),
    platevalue = if_else(is.na(platevalue) | platevalue == 99999, 
                         NA_real_, platevalue),
    hivvalue = case_when(hivvalue == '1' ~ 'Positive',
                         hivvalue == '0' ~ 'Negative',
                         site == 'Jakarta' & hivvalue == '9' ~ 'Not done',
                         site == 'Bandung' & hivvalue == '2' ~ 'Not done',
                         TRUE ~ NA_character_),
    cd4value = if_else(is.na(cd4value) | cd4value == 99999, 
                       NA_real_, cd4value),
    antiigg_res = case_when(antiigg_res == '1' ~ 'Positive',
                            antiigg_res == '0' ~ 'Negative',
                            site == 'Jakarta' & antiigg_res == '9' ~ 'Not done',
                            site == 'Bandung' & antiigg_res == '2' ~ 'Not done',
                            TRUE ~ NA_character_),
    hivstt = case_when(hivstt == '1' ~ 'Positive',
                       hivstt == '0' ~ 'Negative',
                         site == 'Jakarta' & hivstt == '9' ~ 'Unknown',
                         site == 'Bandung' & hivstt == '2' ~ 'Unknown',
                         TRUE ~ NA_character_),
    whcellc1 = if_else(is.na(whcellc1) | whcellc1 == 99999, 
                       NA_real_, whcellc1),
    whcellc2 = if_else(is.na(whcellc2) | whcellc2 == 99999, 
                       NA_real_, whcellc2),
    polycellc1 = if_else(is.na(polycellc1) | polycellc1 == 99999, 
                         NA_real_, polycellc1),
    polycellc2 = if_else(is.na(polycellc2) | polycellc2 == 99999, 
                         NA_real_, polycellc2),
    monocellc1 = if_else(is.na(monocellc1) | monocellc1 == 99999, 
                         NA_real_, monocellc1),
    monocellc2 = if_else(is.na(monocellc2) | monocellc2 == 99999, 
                         NA_real_, monocellc2),
    protein1 = if_else(is.na(protein1) | protein1 == 99999, 
                       NA_real_, protein1),
    protein2 = if_else(is.na(protein2) | protein2 == 99999, 
                       NA_real_, protein2),
    pblglucose1 = if_else(is.na(pblglucose1) | pblglucose1 == 99999, 
                          NA_real_, pblglucose1),
    pblglucose2 = if_else(is.na(pblglucose2) | pblglucose2 == 99999, 
                          NA_real_, pblglucose2),
    ratio_glucose1 = if_else(is.na(ratio_glucose1) | ratio_glucose1 == 99999, 
                             NA_real_, ratio_glucose1),
    ratio_glucose2 = if_else(is.na(ratio_glucose2) | ratio_glucose2 == 99999, 
                             NA_real_, ratio_glucose2),
    crag1 = case_when(crag1 == '1' ~ 'Positive',
                      crag1 == '0' ~ 'Negative',
                      site == 'Jakarta' & crag1 == '9' ~ 'Not done',
                      site == 'Bandung' & crag1 == '2' ~ 'Not done',
                      TRUE ~ NA_character_),
    crag2 = case_when(crag2 == '1' ~ 'Positive',
                      crag2 == '0' ~ 'Negative',
                      site == 'Jakarta' & crag2 == '9' ~ 'Not done',
                      site == 'Bandung' & crag2 == '2' ~ 'Not done',
                      TRUE ~ NA_character_),
    xpert1 = case_when(xpert1 == '1' ~ 'Positive',
                       xpert1 == '0' ~ 'Negative',
                       site == 'Jakarta' & xpert1 == '9' ~ 'Not done',
                       site == 'Bandung' & xpert1 == '2' ~ 'Not done',
                       TRUE ~ NA_character_),
    xpert2 = case_when(xpert2 == '1' ~ 'Positive',
                       xpert2 == '0' ~ 'Negative',
                       site == 'Jakarta' & xpert2 == '9' ~ 'Not done',
                       site == 'Bandung' & xpert2 == '2' ~ 'Not done',
                       TRUE ~ NA_character_),
    xpertrif1 = case_when(xpertrif1 == '1' ~ 'RIF-resistant',
                          xpertrif1 == '0' ~ 'RIF-sensitive',
                          TRUE ~ NA_character_),
    xpertrif2 = case_when(xpertrif2 == '1' ~ 'RIF-resistant',
                          xpertrif2 == '0' ~ 'RIF-sensitive',
                          TRUE ~ NA_character_),
    csfcmv1 = case_when(csfcmv1 == '1' ~ 'Positive',
                        csfcmv1 == '0' ~ 'Negative',
                        site == 'Jakarta' & csfcmv1 == '9' ~ 'Not done',
                        site == 'Bandung' & csfcmv1 == '2' ~ 'Not done',
                        TRUE ~ NA_character_),
    csfcmv2 = case_when(csfcmv2 == '1' ~ 'Positive',
                        csfcmv2 == '0' ~ 'Negative',
                        site == 'Jakarta' & csfcmv2 == '9' ~ 'Not done',
                        site == 'Bandung' & csfcmv2 == '2' ~ 'Not done',
                        TRUE ~ NA_character_),
    csfhsv1 = case_when(csfhsv1 == '1' ~ 'Positive',
                        csfhsv1 == '0' ~ 'Negative',
                        site == 'Jakarta' & csfhsv1 == '9' ~ 'Not done',
                        site == 'Bandung' & csfhsv1 == '2' ~ 'Not done',
                        TRUE ~ NA_character_),
    csfhsv2 = case_when(csfhsv2 == '1' ~ 'Positive',
                        csfhsv2 == '0' ~ 'Negative',
                        site == 'Jakarta' & csfhsv2 == '9' ~ 'Not done',
                        site == 'Bandung' & csfhsv2 == '2' ~ 'Not done',
                        TRUE ~ NA_character_),
    csfebv1 = case_when(csfebv1 == '1' ~ 'Positive',
                        csfebv1 == '0' ~ 'Negative',
                        site == 'Jakarta' & csfebv1 == '9' ~ 'Not done',
                        site == 'Bandung' & csfebv1 == '2' ~ 'Not done',
                        TRUE ~ NA_character_),
    csfebv2 = case_when(csfebv2 == '1' ~ 'Positive',
                        csfebv2 == '0' ~ 'Negative',
                        site == 'Jakarta' & csfebv2 == '9' ~ 'Not done',
                        site == 'Bandung' & csfebv2 == '2' ~ 'Not done',
                        TRUE ~ NA_character_),
    csfvzv1 = case_when(csfvzv1 == '1' ~ 'Positive',
                        csfvzv1 == '0' ~ 'Negative',
                        site == 'Jakarta' & csfvzv1 == '9' ~ 'Not done',
                        site == 'Bandung' & csfvzv1 == '2' ~ 'Not done',
                        TRUE ~ NA_character_),
    csfvzv2 = case_when(csfvzv2 == '1' ~ 'Positive',
                        csfvzv2 == '0' ~ 'Negative',
                        site == 'Jakarta' & csfvzv2 == '9' ~ 'Not done',
                        site == 'Bandung' & csfvzv2 == '2' ~ 'Not done',
                        TRUE ~ NA_character_),
    csfvdrl1 = case_when(csfvdrl1 == '1' ~ 'Positive',
                         csfvdrl1 == '0' ~ 'Negative',
                         site == 'Jakarta' & csfvdrl1 == '9' ~ 'Not done',
                         site == 'Bandung' & csfvdrl1 == '2' ~ 'Not done',
                         TRUE ~ NA_character_),
    csfvdrl2 = case_when(csfvdrl2 == '1' ~ 'Positive',
                         csfvdrl2 == '0' ~ 'Negative',
                         site == 'Jakarta' & csfvdrl2 == '9' ~ 'Not done',
                         site == 'Bandung' & csfvdrl2 == '2' ~ 'Not done',
                         TRUE ~ NA_character_),
    csftpha1 = case_when(csftpha1 == '1' ~ 'Positive',
                         csftpha1 == '0' ~ 'Negative',
                         site == 'Jakarta' & csftpha1 == '9' ~ 'Not done',
                         site == 'Bandung' & csftpha1 == '2' ~ 'Not done',
                         TRUE ~ NA_character_),
    csftpha2 = case_when(csftpha2 == '1' ~ 'Positive',
                         csftpha2 == '0' ~ 'Negative',
                         site == 'Jakarta' & csftpha2 == '9' ~ 'Not done',
                         site == 'Bandung' & csftpha2 == '2' ~ 'Not done',
                         TRUE ~ NA_character_),
    xraynm = case_when(xraynm == '1' ~ TRUE,
                       xraynm == '0' ~ FALSE,
                       TRUE ~ NA),
    xrayinf = case_when(xrayinf == '1' ~ TRUE,
                        xrayinf == '0' ~ FALSE,
                        TRUE ~ NA),
    xraymili = case_when(xraymili == '1' ~ TRUE,
                         xraymili == '0' ~ FALSE,
                         TRUE ~ NA),
    xraycav = case_when(xraycav == '1' ~ TRUE,
                        xraycav == '0' ~ FALSE,
                        TRUE ~ NA),
    bihernia1 = case_when(bihernia1 == '1' ~ TRUE,
                          bihernia1 == '0' ~ FALSE,
                          TRUE ~ NA),
    bihernia2 = case_when(bihernia2 == '1' ~ TRUE,
                          bihernia2 == '0' ~ FALSE,
                          TRUE ~ NA),
    bihernia3 = case_when(bihernia3 == '1' ~ TRUE,
                          bihernia3 == '0' ~ FALSE,
                          TRUE ~ NA),
    bienceph1 = case_when(bienceph1 == '1' ~ TRUE,
                          bienceph1 == '0' ~ FALSE,
                          TRUE ~ NA),
    bienceph2 = case_when(bienceph2 == '1' ~ TRUE,
                          bienceph2 == '0' ~ FALSE,
                          TRUE ~ NA),
    bienceph3 = case_when(bienceph3 == '1' ~ TRUE,
                          bienceph3 == '0' ~ FALSE,
                          TRUE ~ NA),
    staydur = if_else(is.na(staydur) | staydur == 99999, NA_real_, staydur),
    
    outcome = case_when(                                    # Clarify categories
      site == 'Bandung' & outcome == '0' ~ 'Alive',
      site == 'Bandung' & outcome == '1' ~ 'Dead',
      site == 'Bandung' & outcome == '2' ~ 'Discharged',
      site == 'Bandung' & outcome == '3' ~ 'Self-discharged',
      site == 'Bandung' & outcome == '4' ~ 'Referred to another hospital',
      site == 'Bandung' & outcome == '5' ~ 'Hospitalised',
      
      site == 'Jakarta' & outcome == '1' ~ 'Dead',
      site == 'Jakarta' & outcome == '2' ~ 'Self-discharged',
      site == 'Jakarta' & outcome == '3' ~ 'Discharged',
      site == 'Jakarta' & outcome == '4' ~ 'Referred to another hospital'
      
    ),
    
    etiomtuber = case_when(etiomtuber == '1' ~ TRUE,
                           etiomtuber == '0' ~ FALSE,
                           TRUE ~ NA),
    etmtustt = case_when(site == 'Bandung' & etmtustt == '0' ~ 'Definite',
                         site == 'Bandung' & etmtustt == '1' ~ 'Probable',
                         site == 'Bandung' & etmtustt == '2' ~ 'Possible',
                         site == 'Jakarta' & etmtustt == '1' ~ 'Definite',
                         site == 'Jakarta' & etmtustt == '2' ~ 'Probable',
                         site == 'Jakarta' & etmtustt == '3' ~ 'Possible',
                         TRUE ~ NA_character_),
    etitoxoenc = case_when(etitoxoenc == '1' ~ TRUE,
                           etitoxoenc == '0' ~ FALSE,
                           TRUE ~ NA),
    etitoxostt = case_when(site == 'Bandung' & etitoxostt == '0' ~ 'Definite',
                           site == 'Bandung' & etitoxostt == '1' ~ 'Probable',
                           site == 'Bandung' & etitoxostt == '2' ~ 'Possible',
                           site == 'Jakarta' & etitoxostt == '1' ~ 'Definite',
                           site == 'Jakarta' & etitoxostt == '2' ~ 'Probable',
                           site == 'Jakarta' & etitoxostt == '3' ~ 'Possible',
                           TRUE ~ NA_character_),
    eticryp = case_when(eticryp == '1' ~ TRUE,
                        eticryp == '0' ~ FALSE,
                        TRUE ~ NA),
    eticrypstt = case_when(site == 'Bandung' & eticrypstt == '0' ~ 'Definite',
                           site == 'Bandung' & eticrypstt == '1' ~ 'Probable',
                           site == 'Bandung' & eticrypstt == '2' ~ 'Possible',
                           site == 'Jakarta' & eticrypstt == '1' ~ 'Definite',
                           site == 'Jakarta' & eticrypstt == '2' ~ 'Probable',
                           site == 'Jakarta' & eticrypstt == '3' ~ 'Possible',
                           TRUE ~ NA_character_),
    etibac = case_when(etibac == '1' ~ TRUE,
                       etibac == '0' ~ FALSE,
                       TRUE ~ NA),
    etibacstt = case_when(site == 'Bandung' & etibacstt == '0' ~ 'Definite',
                          site == 'Bandung' & etibacstt == '1' ~ 'Probable',
                          site == 'Bandung' & etibacstt == '2' ~ 'Possible',
                          site == 'Jakarta' & etibacstt == '1' ~ 'Definite',
                          site == 'Jakarta' & etibacstt == '2' ~ 'Probable',
                          site == 'Jakarta' & etibacstt == '3' ~ 'Possible',
                          TRUE ~ NA_character_),
    etivence = case_when(etivence == '1' ~ TRUE,
                         etivence == '0' ~ FALSE,
                         TRUE ~ NA),
    etivencestt = case_when(site == 'Bandung' & etivencestt == '0' ~ 'Definite',
                            site == 'Bandung' & etivencestt == '1' ~ 'Probable',
                            site == 'Bandung' & etivencestt == '2' ~ 'Possible',
                            site == 'Jakarta' & etivencestt == '1' ~ 'Definite',
                            site == 'Jakarta' & etivencestt == '2' ~ 'Probable',
                            site == 'Jakarta' & etivencestt == '3' ~ 'Possible',
                            TRUE ~ NA_character_),
    etiothba = case_when(etiothba == '1' ~ TRUE,
                         etiothba == '0' ~ FALSE,
                         TRUE ~ NA),
    etiothmuco = case_when(etiothmuco == '1' ~ TRUE,
                           etiothmuco == '0' ~ FALSE,
                           TRUE ~ NA),
    etiothbm = case_when(etiothbm == '1' ~ TRUE,
                         etiothbm == '0' ~ FALSE,
                         TRUE ~ NA),
    etiothneu = case_when(etiothneu == '1' ~ TRUE,
                          etiothneu == '0' ~ FALSE,
                          TRUE ~ NA),
    etiohtlym = case_when(etiohtlym == '1' ~ TRUE,
                          etiohtlym == '0' ~ FALSE,
                          TRUE ~ NA),
    etiohnmdar = case_when(etiohnmdar == '1' ~ TRUE,
                           etiohnmdar == '0' ~ FALSE,
                           TRUE ~ NA),
    paticond = case_when(
      site == 'Bandung' & paticond == '0' ~ 'Alive',
      site == 'Bandung' & paticond == '1' ~ 'Dead',
      site == 'Bandung' & paticond == '2' ~ 'Lost to follow up',
      site == 'Jakarta' & paticond == '1' ~ 'Alive',
      site == 'Jakarta' & paticond == '2' ~ 'Dead',
      site == 'Jakarta' & paticond == '3' ~ 'Lost to follow up',
      TRUE ~ NA_character_
      ),
    iscnsinfec = case_when(
      iscnsinfec == '1' ~ TRUE,
      iscnsinfec == '0' ~ FALSE,
      TRUE ~ NA
    ),
    is18 = case_when(
      is18 == '1' ~ TRUE,
      is18 == '0' ~ FALSE,
      TRUE ~ NA
    ),
    issigned = case_when(
      issigned == '1' ~ TRUE,
      issigned == '0' ~ FALSE,
      TRUE ~ NA
    ),
    admisdtc = ymd(admisdtc),
    admistime = case_when(
     site == 'Jakarta' ~ as.character(admistime),
     site == 'Bandung' ~ str_sub(admistime, start = 12, end = -1),
     TRUE ~ NA_character_
    ),
    admistime = hms(admistime),
    neuroinfecdtc = ymd(neuroinfecdtc),
    neuroinfectime = case_when(
      site == 'Jakarta' ~ as.character(neuroinfectime),
      site == 'Bandung' ~ str_sub(neuroinfectime, start = 12, end = -1),
      TRUE ~ NA_character_
    ),
    neuroinfectime = hms(neuroinfectime),
    fstdosend = case_when(
      site == 'Jakarta' & fstdosend == 'FALSE' ~ 'Done',
      site == 'Jakarta' & fstdosend == 'TRUE ' ~ 'Not done',
      site == 'Bandung' & fstdosend == '1' ~ 'Done',
      site == 'Bandung' & fstdosend == '0' ~ 'Not done',
      TRUE ~ NA_character_
    ),
    fstdosedtc = ymd(fstdosedtc),
    fstdosetime = case_when(
      site == 'Jakarta' ~ as.character(fstdosetime),
      site == 'Bandung' ~ str_sub(fstdosetime, start = 12, end = -1),
      TRUE ~ NA_character_
    ),
    fstdosetime = hms(fstdosetime),
    lumpuncnd = case_when(
      site == 'Jakarta' & lumpuncnd == 'FALSE' ~ 'Done',
      site == 'Jakarta' & lumpuncnd == 'TRUE ' ~ 'Not done',
      site == 'Bandung' & lumpuncnd == '1' ~ 'Done',
      site == 'Bandung' & lumpuncnd == '0' ~ 'Not done',
      TRUE ~ NA_character_
    ),
    lumpuncdtc = ymd(lumpuncdtc),
    lunpunctime = case_when(
      site == 'Jakarta' ~ as.character(lunpunctime),
      site == 'Bandung' ~ str_sub(lunpunctime, start = 12, end = -1),
      TRUE ~ NA_character_
    ),
    lunpunctime = hms(lunpunctime),
    enrolldtc = ymd(enrolldtc),
    enrolltime = case_when(
      site == 'Jakarta' ~ as.character(enrolltime),
      site == 'Bandung' ~ str_sub(enrolltime, start = 12, end = -1),
      TRUE ~ NA_character_
    ),
    enrolltime = hms(enrolltime),
    isrecrbf = case_when(
      isrecrbf == '1' ~ TRUE,
      isrecrbf == '0' ~ FALSE,
      TRUE ~ NA 
    ),
    mob = case_when(
       site == 'Jakarta' ~ as.numeric(mob),
       site == 'Bandung' ~ str_sub(dob, start = 6, end = 7) |> as.numeric(),
       TRUE ~ NA_real_
    ),
    yob = case_when(
      site == 'Jakarta' ~ as.numeric(yob),
      site == 'Bandung' ~ str_sub(dob, start = 1, end = 4) |> as.numeric(),
      TRUE ~ NA_real_
    ),
    dob = case_when(
      site == 'Jakarta' ~ as.numeric(dob),
      site == 'Bandung' ~ str_sub(dob, start = -2, end = -1) |> as.numeric(),
      TRUE ~ NA_real_
    ),
    studypl = case_when(
       studypl == '1' ~ as.numeric(studypl),
       studypl == '2' ~ as.numeric(studypl),
       studypl == '3' ~ as.numeric(studypl),
       TRUE ~ NA_real_
    ),
    refstt = case_when(
      refstt == '1' ~ as.numeric(refstt),
      refstt == '2' ~ as.numeric(refstt),
      refstt == '3' ~ as.numeric(refstt),
      TRUE ~ NA_real_
    ),
    fstsymdtc = ymd(fstsymdtc),
    fevercomp = if_else(fevercomp == '1', TRUE, FALSE),
    headcomp = if_else(headcomp == '1', TRUE, FALSE),
    vomitcomp = if_else(vomitcomp == '1', TRUE, FALSE),
    alconcomp = if_else(alconcomp == '1', TRUE, FALSE),
    lethsym = case_when(
      lethsym == '1' ~ as.numeric(lethsym),
      lethsym == '0' ~ as.numeric(lethsym),
      lethsym %in% c('8', '9') ~ 2,
      TRUE ~ NA_real_
    ),
    lethcomp = if_else(lethcomp == '1', TRUE, FALSE),
    lethday = case_when(
      lethday == 99999 ~ NA_real_,
      is.numeric(lethday) ~ as.numeric(lethday),
      TRUE ~ NA_real_
    ),
    bechcomp = if_else(bechcomp == '1', TRUE, FALSE),
    moabsym = case_when(
      moabsym == '1' ~ as.numeric(moabsym),
      moabsym == '0' ~ as.numeric(moabsym),
      moabsym %in% c('8', '9') ~ 2,
      TRUE ~ NA_real_
    ),
    moabcomp = if_else(moabcomp == '1', TRUE, FALSE),
    moabday = case_when(
      moabday == 99999 ~ NA_real_,
      is.numeric(moabday) ~ as.numeric(moabday),
      TRUE ~ NA_real_
    ),
    seabsym = case_when(
      seabsym == '1' ~ as.numeric(seabsym),
      seabsym == '0' ~ as.numeric(seabsym),
      seabsym %in% c('8', '9') ~ 2,
      TRUE ~ NA_real_
    ),
    seabcomp = if_else(seabcomp == '1', TRUE, FALSE),
    seabday = case_when(
      seabday == 99999 ~ NA_real_,
      is.numeric(seabday) ~ as.numeric(seabday),
      TRUE ~ NA_real_
    ),
    cranpsym = case_when(
      cranpsym == '1' ~ as.numeric(cranpsym),
      cranpsym == '0' ~ as.numeric(cranpsym),
      cranpsym %in% c('8', '9') ~ 2,
      TRUE ~ NA_real_
    ),
    cranpcomp = if_else(cranpcomp == '1', TRUE, FALSE),
    cranpday = case_when(
      cranpday == 99999 ~ NA_real_,
      is.numeric(cranpday) ~ as.numeric(cranpday),
      TRUE ~ NA_real_
    ),
    seizucomp = if_else(seizucomp == '1', TRUE, FALSE),
    seipattern = case_when(
      site == 'Jakarta' & seipattern == '1' ~ 0,
      site == 'Jakarta' & seipattern == '2' ~ 1,
      site == 'Bandung' & seipattern == '0' ~ 0,
      site == 'Bandung' & seipattern == '1' ~ 1,
      seipattern %in% c('8', '9') ~ 2,
    ),
    seiwitms = if_else(seiwitms == '1', TRUE, FALSE),
    seizufre = case_when(
      seizufre == '0' ~ 0,
      seizufre == '1' ~ 1,
      seizufre == '2' ~ 2,
      seizufre %in% c('8', '9') ~ 3,
      TRUE ~ NA_real_
    )
  ) |>
  
  # Make sure all categories are present despite missingness
  mutate(
    seizufre = factor(seizufre,
                      levels = c(0, 1, 2, 3),
                      labels = c('No', 'Once', 'Repeated', 'Unknown')),
    seipattern = factor(seipattern,
                        levels = c(0, 1, 2),
                        labels = c('Focal', 'General', 'Unknown')),
    cranpsym = factor(cranpsym,
                      levels = c(0, 1, 2),
                      labels = c('No', 'Yes', 'Unknown')),
    seabsym = factor(seabsym,
                     levels = c(0, 1, 2),
                     labels = c('No', 'Yes', 'Unknown')),
    moabsym = factor(moabsym,
                     levels = c(0, 1, 2),
                     labels = c('No', 'Yes', 'Unknown')),
    lethsym = factor(lethsym,
                     levels = c(0, 1, 2),
                     labels = c('No', 'Yes', 'Unknown')),
    refstt = factor(refstt,
                    levels = c(1, 2, 3),
                    labels = c('Self-referral',
                               'Hospital referral',
                               'Primary health care')),
    studypl = factor(studypl,
                     levels = c(1, 2, 3),
                     labels = c('ER', 'Ward', 'Outpatient')),
    fstdosend = factor(fstdosend,
                       levels = c('Done', 'Not done'),
                       labels = c('Done', 'Not done')),
    lumpuncnd = factor(lumpuncnd,
                       levels = c('Done', 'Not done'),
                       labels = c('Done', 'Not done')),
    sex = factor(sex,
                 levels = c('Female', 'Male'),
                 labels = c('Female', 'Male')),
    hivvalue = factor(hivvalue,
                      levels = c('Positive', 'Negative', 'Not done'),
                      labels = c('Positive', 'Negative', 'Not done')),
    antiigg_res = factor(antiigg_res,
                         levels = c('Positive', 'Negative', 'Not done'),
                         labels = c('Positive', 'Negative', 'Not done')),
    hivstt = factor(hivstt,
                    levels = c('Positive', 'Negative', 'Not done'),
                    labels = c('Positive', 'Negative', 'Not done')),
    crag1 = factor(crag1,
                   levels = c('Positive', 'Negative', 'Not done'),
                   labels = c('Positive', 'Negative', 'Not done')),
    crag2 = factor(crag2,
                   levels = c('Positive', 'Negative', 'Not done'),
                   labels = c('Positive', 'Negative', 'Not done')),
    xpert1 = factor(xpert1,
                    levels = c('Positive', 'Negative', 'Not done'),
                    labels = c('Positive', 'Negative', 'Not done')),
    xpert2 = factor(xpert2,
                    levels = c('Positive', 'Negative', 'Not done'),
                    labels = c('Positive', 'Negative', 'Not done')),
    xpertrif1 = factor(xpertrif1,
                       levels = c('RIF-resistant', 'RIF-sensitive'),
                       labels = c('RIF-resistant', 'RIF-sensitive')),
    xpertrif2 = factor(xpertrif2,
                       levels = c('RIF-resistant', 'RIF-sensitive'),
                       labels = c('RIF-resistant', 'RIF-sensitive')),
    csfcmv1 = factor(csfcmv1,
                     levels = c('Positive', 'Negative', 'Not done'),
                     labels = c('Positive', 'Negative', 'Not done')),
    csfcmv2 = factor(csfcmv2,
                     levels = c('Positive', 'Negative', 'Not done'),
                     labels = c('Positive', 'Negative', 'Not done')),
    csfhsv1 = factor(csfhsv1,
                     levels = c('Positive', 'Negative', 'Not done'),
                     labels = c('Positive', 'Negative', 'Not done')),
    csfhsv2 = factor(csfhsv2,
                     levels = c('Positive', 'Negative', 'Not done'),
                     labels = c('Positive', 'Negative', 'Not done')),
    csfebv1 = factor(csfebv1,
                     levels = c('Positive', 'Negative', 'Not done'),
                     labels = c('Positive', 'Negative', 'Not done')),
    csfebv2 = factor(csfebv2,
                     levels = c('Positive', 'Negative', 'Not done'),
                     labels = c('Positive', 'Negative', 'Not done')),
    csfvzv1 = factor(csfvzv1,
                     levels = c('Positive', 'Negative', 'Not done'),
                     labels = c('Positive', 'Negative', 'Not done')),
    csfvzv2 = factor(csfvzv2,
                     levels = c('Positive', 'Negative', 'Not done'),
                     labels = c('Positive', 'Negative', 'Not done')),
    csfvdrl1 = factor(csfvdrl1,
                      levels = c('Positive', 'Negative', 'Not done'),
                      labels = c('Positive', 'Negative', 'Not done')),
    csfvdrl2 = factor(csfvdrl2,
                      levels = c('Positive', 'Negative', 'Not done'),
                      labels = c('Positive', 'Negative', 'Not done')),
    csftpha1 = factor(csftpha1,
                      levels = c('Positive', 'Negative', 'Not done'),
                      labels = c('Positive', 'Negative', 'Not done')),
    csftpha2 = factor(csftpha2,
                      levels = c('Positive', 'Negative', 'Not done'),
                      labels = c('Positive', 'Negative', 'Not done')),
    outcome = factor(outcome,
                     levels = c('Alive', 'Dead', 'Discharged',
                                'Self-discharged',
                                'Referred to another hospital',
                                'Hospitalised'),
                     labels = c('Alive', 'Dead', 'Discharged',
                                'Self-discharged',
                                'Referred to another hospital',
                                'Hospitalised')),
    etmtustt = factor(etmtustt,
                      levels = c('Definite', 'Probable', 'Possible'),
                      labels = c('Definite', 'Probable', 'Possible')),
    etitoxostt = factor(etitoxostt,
                        levels = c('Definite', 'Probable', 'Possible'),
                        labels = c('Definite', 'Probable', 'Possible')),
    eticrypstt = factor(eticrypstt,
                        levels = c('Definite', 'Probable', 'Possible'),
                        labels = c('Definite', 'Probable', 'Possible')),
    etibacstt = factor(etibacstt,
                       levels = c('Definite', 'Probable', 'Possible'),
                       labels = c('Definite', 'Probable', 'Possible')),
    etivencestt = factor(etivencestt,
                         levels = c('Definite', 'Probable', 'Possible'),
                         labels = c('Definite', 'Probable', 'Possible')),
    paticond = factor(paticond,
                      levels = c('Alive', 'Dead', 'Lost to follow up'),
                      labels = c('Alive', 'Dead', 'Lost to follow up'))) |>
  
  # Derived variables
  rowwise() |>
  mutate(comppare = sum(c_across(hemipare:monopare), na.rm = TRUE)) |>
  ungroup() |>
  mutate(comppare = if_else(comppare >= 1, TRUE, FALSE)) |>
  
  # Include or exclude observed, cleaned variables
  mutate(
    hivstt = case_when(
      site == 'Jakarta' ~ hivstt,
      site == 'Bandung' ~ hivvalue,
      TRUE ~ NA_integer_
    )
  )
  
# Label variables
var_label(ibis) <- list(
  site = 'Study site',
  siteid = 'Study site ID',
  subjid = 'Unique patient ID',
  age = 'Age (years)',
  sex = 'Biological sex',
  symdays = 'Duration of symptoms (days)',
  feversym = 'Fever',
  feverday = 'Duration of fever (days)',
  headsym = 'Headache',
  headday = 'Duration of headache (days)',
  vomitsym = 'Vomiting',
  vomitday = 'Duration of vomiting (days)',
  alconsym = 'Altered conciousness',
  alconday = 'Duration of altered conciousness (days)',
  bechsym = 'Behavioural change',
  bechday = 'Duration of behavioural change (days)',
  seizusym = 'Seizure',
  seizuonset = 'Onset prior to baseline (days)',
  cough = 'Coughing',
  htemp = 'Highest recorded temperature at baseline (celcius)',
  gcs = 'Total GCS at baseline',
  palsy = 'Cranial nerve palsy',
  papille = 'Papilledema',
  neckstiff = 'Neck stiffness',
  motordef = 'Motor deficits',
  hemipare = 'Hemiparesis',
  parapare = 'Paraparesis',
  tetrapare = 'Tetraparesis',
  monopare = 'Monoparesis',
  hemovalue = 'Haemoglobin level (g/dL)',
  wcellcvalue = 'White blood cell count (in 1000 cells/μL)',
  platevalue = 'Platelet count (in 1000 cells/μL)',
  hivvalue = 'HIV test',
  cd4value = 'CD4 cell count (cells/L)',
  antiigg_res = 'Antitoxoplasma IgG',
  hivstt = 'HIV status',
  whcellc1 = 'Total white cell count (cells/μL), 1',
  whcellc2 = 'Total white cell count (cells/μL), 2',
  polycellc1 = 'Polymorphonuclear cell count (cells/μL), 1',
  polycellc2 = 'Polymorphonuclear cell count (cells/μL), 2',
  monocellc1 = 'Mononuclear cell count (cells/μL), 1',
  monocellc2 = 'Mononuclear cell count (cells/μL), 2',
  protein1 = 'Total protein (mg/dL), 1',
  protein2 = 'Total protein (mg/dL), 2',
  pblglucose1 = 'Paired blood glucose (mg/dL), 1',
  pblglucose2 = 'Paired blood glucose (mg/dL), 2',
  ratio_glucose1 = 'Glucose ratio, 1',
  ratio_glucose2 = 'Glucose ratio, 2',
  crag1 = 'Cryptococcal antigen test, 1',
  crag2 = 'Cryptococcal antigen test, 2',
  xpert1 = 'Gene Xpert, 1',
  xpert2 = 'Gene Xpert, 2',
  xpertrif1 = 'RIF resistance, 1',
  xpertrif2 = 'RIF resistance, 2',
  csfcmv1 = 'CSF PCR for CMV, 1',
  csfcmv2 = 'CSF PCR for CMV, 2',
  csfhsv1 = 'CSF PCR for HSV, 1',
  csfhsv2 = 'CSF PCR for HSV, 2',
  csfebv1 = 'CSF PCR for EBV, 1',
  csfebv2 = 'CSF PCR for EBV, 2',
  csfvzv1 = 'CSF PCR for VZV, 1',
  csfvzv2 = 'CSF PCR for VZV, 2',
  csfvdrl1 = 'CSF PCR for VDRL, 1',
  csfvdrl2 = 'CSF PCR for VDRL, 2',
  csftpha1 = 'CSF PCR for TPHA, 1',
  csftpha2 = 'CSF PCR for TPHA, 2',
  xraynm = 'Chest X-ray: Normal',
  xrayinf = 'Chest X-ray: Infiltrates',
  xraymili = 'Chest X-ray: Miliary',
  xraycav = 'Chest X-ray: Cavities',
  xray_ores = 'Chest X-ray: Other',
  bihernia1 = 'Herniation, 1',
  bihernia2 = 'Herniation, 2',
  bihernia3 = 'Herniation, 3',
  bienceph1 = 'Encephalitis, 1',
  bienceph2 = 'Encephalitis, 2',
  bienceph3 = 'Encephalitis, 3',
  staydur = 'Duration of stay (days)',
  outcome = 'Outcome',
  nonneuspec = 'Non-neuroinfection case, specified',
  etiomtuber = 'M. tuberculosis',
  etmtustt = 'M. tuberculosis status',
  etitoxoenc = 'Toxoplasma encephalitis',
  etitoxostt = 'Toxoplasma encephalitis status',
  eticryp = 'Cryptococcal meningitis',
  eticrypstt = 'Cryptococcal meningitis status',
  etibac = 'Bacterial meningitis',
  etibacstt = 'Bacterial meningitis status',
  etivence = 'Viral encephalitis',
  etivencestt = 'Viral encephalitis status',
  etiothba = 'Brain abcess',
  etiothmuco = 'Mucormycosis',
  etiothbm = 'Bacterial meningitis',
  etiothneu = 'Neurosyphilis',
  etiohtlym = 'Lymphoma',
  etiohnmdar = 'NMDAR encephalitis',
  etioothspec = 'Other aetiology',
  paticond = "Patient's condition",
  comppare = 'Presence of any paresis',
  
  initial = "Patient's initial",
  
)

# Exclude variables
ibis <- ibis |>
  select(-c(hivvalue))

# Take a look at the cleaned dataset
glimpse(ibis)

# Extended variables ------------------------------------------------------



# Save --------------------------------------------------------------------

ibis |> write_rds(here('0-data', 'ibis_all-cleaned.rds')) # R
ibis |> write_sav(here('0-data', 'ibis_all-cleaned.sav')) # SPSS
ibis |> write_dta(here('0-data', 'ibis_all-cleaned.dta')) # Stata

# Appendix ----------------------------------------------------------------

sessioninfo::platform_info()



















